name = "requiem-api-management"
main = "src/index.ts"
compatibility_date = "2025-0f-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[[kv_namespaces]]
binding = "KV"
id = "7cc847da3f3143b2ba8f7c531f416b35"

[[d1_databases]]
binding = "DB"
database_name = "requiem-usage"
database_id = "8cc5cae5-caff-4878-80f7-94eed1931ea8"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[dev]
port = 6001

[vars]
ENVIRONMENT = "development"

[env.production]
name = "requiem-api-management-production"
workers_dev = false
preview_urls = false

[[env.production.routes]]
pattern = "api-management.requiems.xyz"
custom_domain = true

[env.production.vars]
ENVIRONMENT = "production"

[[env.production.kv_namespaces]]
binding = "KV"
id = "7cc847da3f3143b2ba8f7c531f416b35"

[[env.production.d1_databases]]
binding = "DB"
database_name = "requiem-usage"
database_id = "8cc5cae5-caff-4878-80f7-94eed1931ea8"
