package chucknorris

// facts is the built-in Chuck Norris fact database.
var facts = []string{
	"Chuck Norris can divide by zero.",
	"Chuck Norris counted to infinity. Twice.",
	"Chuck Norris can hear silence.",
	"Chuck Norris doesn't read books — he stares them down until he gets the information he wants.",
	"Time waits for no man. Unless that man is Chuck Norris.",
	"Chuck Norris can speak Braille.",
	"Chuck Norris can kill two stones with one bird.",
	"Chuck Norris's tears cure cancer. Too bad he has never cried.",
	"Chuck Norris once kicked a horse in the chin. Its descendants are known today as giraffes.",
	"Chuck Norris can build a snowman out of rain.",
	"Chuck Norris destroyed the periodic table because he only recognizes the element of surprise.",
	"When Chuck Norris enters a room, he doesn't turn the lights on — he turns the dark off.",
	"Chuck Norris once had a heart attack. His heart lost.",
	"Chuck Norris doesn't breathe — he holds air hostage.",
	"Chuck Norris can slam a revolving door.",
	"Chuck Norris once won a game of Connect Four in three moves.",
	"Chuck Norris can set ants on fire with a magnifying glass — at night.",
	"Chuck Norris's calendar goes straight from March 31st to April 2nd because nobody fools Chuck Norris.",
	"Chuck Norris can strangle you with a cordless phone.",
	"Outer space exists because it's afraid to be on the same planet as Chuck Norris.",
	"Chuck Norris has a grizzly bear carpet in his room. The bear isn't dead — it's just afraid to move.",
	"Chuck Norris doesn't wear a watch. He decides what time it is.",
	"Chuck Norris can unscramble an egg.",
	"Chuck Norris once climbed Mount Everest in 15 minutes, 14 of which he spent napping.",
	"When Chuck Norris does a pushup, he isn't lifting himself up — he's pushing the Earth down.",
	"Chuck Norris can win a game of chess in one move.",
	"Chuck Norris can tie his shoes with his feet.",
	"Death once had a near-Chuck-Norris experience.",
	"Chuck Norris doesn't need a debugger — he stares down the code until it confesses.",
	"Chuck Norris can compile errors.",
}
