package timezone

// cityTimezones maps lowercase city names to IANA timezone identifiers.
var cityTimezones = map[string]string{
	// Africa
	"abidjan":       "Africa/Abidjan",
	"accra":         "Africa/Accra",
	"addis ababa":   "Africa/Addis_Ababa",
	"algiers":       "Africa/Algiers",
	"cairo":         "Africa/Cairo",
	"cape town":     "Africa/Johannesburg",
	"casablanca":    "Africa/Casablanca",
	"dakar":         "Africa/Dakar",
	"dar es salaam": "Africa/Dar_es_Salaam",
	"johannesburg":  "Africa/Johannesburg",
	"kampala":       "Africa/Kampala",
	"khartoum":      "Africa/Khartoum",
	"kinshasa":      "Africa/Kinshasa",
	"lagos":         "Africa/Lagos",
	"lusaka":        "Africa/Lusaka",
	"nairobi":       "Africa/Nairobi",
	"tripoli":       "Africa/Tripoli",
	"tunis":         "Africa/Tunis",

	// Americas
	"anchorage":       "America/Anchorage",
	"bogota":          "America/Bogota",
	"buenos aires":    "America/Argentina/Buenos_Aires",
	"caracas":         "America/Caracas",
	"chicago":         "America/Chicago",
	"denver":          "America/Denver",
	"guadalajara":     "America/Mexico_City",
	"guatemala city":  "America/Guatemala",
	"guayaquil":       "America/Guayaquil",
	"havana":          "America/Havana",
	"honolulu":        "Pacific/Honolulu",
	"la paz":          "America/La_Paz",
	"lima":            "America/Lima",
	"los angeles":     "America/Los_Angeles",
	"managua":         "America/Managua",
	"mexico city":     "America/Mexico_City",
	"miami":           "America/New_York",
	"monterrey":       "America/Monterrey",
	"montevideo":      "America/Montevideo",
	"montreal":        "America/Toronto",
	"new york":        "America/New_York",
	"panama city":     "America/Panama",
	"phoenix":         "America/Phoenix",
	"port of spain":   "America/Port_of_Spain",
	"quito":           "America/Guayaquil",
	"san jose":        "America/Costa_Rica",
	"san juan":        "America/Puerto_Rico",
	"santiago":        "America/Santiago",
	"santo domingo":   "America/Santo_Domingo",
	"sao paulo":       "America/Sao_Paulo",
	"tegucigalpa":     "America/Tegucigalpa",
	"toronto":         "America/Toronto",
	"vancouver":       "America/Vancouver",
	"washington":      "America/New_York",
	"washington d.c.": "America/New_York",

	// Asia
	"abu dhabi":    "Asia/Dubai",
	"almaty":       "Asia/Almaty",
	"amman":        "Asia/Amman",
	"ankara":       "Europe/Istanbul",
	"baku":         "Asia/Baku",
	"bangkok":      "Asia/Bangkok",
	"beijing":      "Asia/Shanghai",
	"beirut":       "Asia/Beirut",
	"colombo":      "Asia/Colombo",
	"dhaka":        "Asia/Dhaka",
	"doha":         "Asia/Qatar",
	"dubai":        "Asia/Dubai",
	"hanoi":        "Asia/Ho_Chi_Minh",
	"ho chi minh":  "Asia/Ho_Chi_Minh",
	"hong kong":    "Asia/Hong_Kong",
	"islamabad":    "Asia/Karachi",
	"istanbul":     "Europe/Istanbul",
	"jakarta":      "Asia/Jakarta",
	"jerusalem":    "Asia/Jerusalem",
	"kabul":        "Asia/Kabul",
	"karachi":      "Asia/Karachi",
	"kathmandu":    "Asia/Kathmandu",
	"kolkata":      "Asia/Kolkata",
	"kuala lumpur": "Asia/Kuala_Lumpur",
	"kuwait city":  "Asia/Kuwait",
	"lahore":       "Asia/Karachi",
	"manila":       "Asia/Manila",
	"muscat":       "Asia/Muscat",
	"new delhi":    "Asia/Kolkata",
	"nicosia":      "Asia/Nicosia",
	"osaka":        "Asia/Tokyo",
	"phnom penh":   "Asia/Phnom_Penh",
	"riyadh":       "Asia/Riyadh",
	"seoul":        "Asia/Seoul",
	"shanghai":     "Asia/Shanghai",
	"singapore":    "Asia/Singapore",
	"taipei":       "Asia/Taipei",
	"tashkent":     "Asia/Tashkent",
	"tbilisi":      "Asia/Tbilisi",
	"tehran":       "Asia/Tehran",
	"tel aviv":     "Asia/Jerusalem",
	"thimphu":      "Asia/Thimphu",
	"tokyo":        "Asia/Tokyo",
	"ulaanbaatar":  "Asia/Ulaanbaatar",
	"vientiane":    "Asia/Vientiane",
	"yangon":       "Asia/Rangoon",
	"yerevan":      "Asia/Yerevan",

	// Europe
	"amsterdam":  "Europe/Amsterdam",
	"athens":     "Europe/Athens",
	"barcelona":  "Europe/Madrid",
	"belgrade":   "Europe/Belgrade",
	"berlin":     "Europe/Berlin",
	"bern":       "Europe/Zurich",
	"bratislava": "Europe/Bratislava",
	"brussels":   "Europe/Brussels",
	"bucharest":  "Europe/Bucharest",
	"budapest":   "Europe/Budapest",
	"chisinau":   "Europe/Chisinau",
	"copenhagen": "Europe/Copenhagen",
	"dublin":     "Europe/Dublin",
	"edinburgh":  "Europe/London",
	"helsinki":   "Europe/Helsinki",
	"kiev":       "Europe/Kyiv",
	"kyiv":       "Europe/Kyiv",
	"lisbon":     "Europe/Lisbon",
	"ljubljana":  "Europe/Ljubljana",
	"london":     "Europe/London",
	"luxembourg": "Europe/Luxembourg",
	"madrid":     "Europe/Madrid",
	"minsk":      "Europe/Minsk",
	"monaco":     "Europe/Monaco",
	"moscow":     "Europe/Moscow",
	"nicosia eu": "Asia/Nicosia",
	"oslo":       "Europe/Oslo",
	"paris":      "Europe/Paris",
	"podgorica":  "Europe/Podgorica",
	"prague":     "Europe/Prague",
	"riga":       "Europe/Riga",
	"rome":       "Europe/Rome",
	"sarajevo":   "Europe/Sarajevo",
	"skopje":     "Europe/Skopje",
	"sofia":      "Europe/Sofia",
	"stockholm":  "Europe/Stockholm",
	"tallinn":    "Europe/Tallinn",
	"tirana":     "Europe/Tirane",
	"vaduz":      "Europe/Vaduz",
	"valletta":   "Europe/Malta",
	"vienna":     "Europe/Vienna",
	"vilnius":    "Europe/Vilnius",
	"warsaw":     "Europe/Warsaw",
	"zagreb":     "Europe/Zagreb",
	"zurich":     "Europe/Zurich",

	// Oceania
	"auckland":     "Pacific/Auckland",
	"brisbane":     "Australia/Brisbane",
	"canberra":     "Australia/Sydney",
	"melbourne":    "Australia/Melbourne",
	"perth":        "Australia/Perth",
	"port moresby": "Pacific/Port_Moresby",
	"suva":         "Pacific/Fiji",
	"sydney":       "Australia/Sydney",
	"wellington":   "Pacific/Auckland",
}
