package emoji

// emojis is an embedded dataset derived from the Unicode CLDR / unicode.org
// emoji specification. Each entry carries the rendered glyph, its CLDR short
// name (snake_case), Unicode category, and code-point in U+XXXX notation.
var emojis = []Emoji{
	// Smileys & Emotion
	{Emoji: "😀", Name: "grinning_face", Category: "Smileys & Emotion", Unicode: "U+1F600"},
	{Emoji: "😃", Name: "grinning_face_with_big_eyes", Category: "Smileys & Emotion", Unicode: "U+1F603"},
	{Emoji: "😄", Name: "grinning_face_with_smiling_eyes", Category: "Smileys & Emotion", Unicode: "U+1F604"},
	{Emoji: "😁", Name: "beaming_face_with_smiling_eyes", Category: "Smileys & Emotion", Unicode: "U+1F601"},
	{Emoji: "😆", Name: "grinning_squinting_face", Category: "Smileys & Emotion", Unicode: "U+1F606"},
	{Emoji: "😅", Name: "grinning_face_with_sweat", Category: "Smileys & Emotion", Unicode: "U+1F605"},
	{Emoji: "🤣", Name: "rolling_on_the_floor_laughing", Category: "Smileys & Emotion", Unicode: "U+1F923"},
	{Emoji: "😂", Name: "face_with_tears_of_joy", Category: "Smileys & Emotion", Unicode: "U+1F602"},
	{Emoji: "🙂", Name: "slightly_smiling_face", Category: "Smileys & Emotion", Unicode: "U+1F642"},
	{Emoji: "🙃", Name: "upside_down_face", Category: "Smileys & Emotion", Unicode: "U+1F643"},
	{Emoji: "😉", Name: "winking_face", Category: "Smileys & Emotion", Unicode: "U+1F609"},
	{Emoji: "😊", Name: "smiling_face_with_smiling_eyes", Category: "Smileys & Emotion", Unicode: "U+1F60A"},
	{Emoji: "😇", Name: "smiling_face_with_halo", Category: "Smileys & Emotion", Unicode: "U+1F607"},
	{Emoji: "🥰", Name: "smiling_face_with_hearts", Category: "Smileys & Emotion", Unicode: "U+1F970"},
	{Emoji: "😍", Name: "smiling_face_with_heart_eyes", Category: "Smileys & Emotion", Unicode: "U+1F60D"},
	{Emoji: "🤩", Name: "star_struck", Category: "Smileys & Emotion", Unicode: "U+1F929"},
	{Emoji: "😘", Name: "face_blowing_a_kiss", Category: "Smileys & Emotion", Unicode: "U+1F618"},
	{Emoji: "😗", Name: "kissing_face", Category: "Smileys & Emotion", Unicode: "U+1F617"},
	{Emoji: "😚", Name: "kissing_face_with_closed_eyes", Category: "Smileys & Emotion", Unicode: "U+1F61A"},
	{Emoji: "😙", Name: "kissing_face_with_smiling_eyes", Category: "Smileys & Emotion", Unicode: "U+1F619"},
	{Emoji: "🥲", Name: "smiling_face_with_tear", Category: "Smileys & Emotion", Unicode: "U+1F972"},
	{Emoji: "😋", Name: "face_savoring_food", Category: "Smileys & Emotion", Unicode: "U+1F60B"},
	{Emoji: "😛", Name: "face_with_tongue", Category: "Smileys & Emotion", Unicode: "U+1F61B"},
	{Emoji: "😜", Name: "winking_face_with_tongue", Category: "Smileys & Emotion", Unicode: "U+1F61C"},
	{Emoji: "🤪", Name: "zany_face", Category: "Smileys & Emotion", Unicode: "U+1F92A"},
	{Emoji: "😝", Name: "squinting_face_with_tongue", Category: "Smileys & Emotion", Unicode: "U+1F61D"},
	{Emoji: "🤑", Name: "money_mouth_face", Category: "Smileys & Emotion", Unicode: "U+1F911"},
	{Emoji: "🤗", Name: "smiling_face_with_open_hands", Category: "Smileys & Emotion", Unicode: "U+1F917"},
	{Emoji: "🤭", Name: "face_with_hand_over_mouth", Category: "Smileys & Emotion", Unicode: "U+1F92D"},
	{Emoji: "🤫", Name: "shushing_face", Category: "Smileys & Emotion", Unicode: "U+1F92B"},
	{Emoji: "🤔", Name: "thinking_face", Category: "Smileys & Emotion", Unicode: "U+1F914"},
	{Emoji: "🤐", Name: "zipper_mouth_face", Category: "Smileys & Emotion", Unicode: "U+1F910"},
	{Emoji: "🤨", Name: "face_with_raised_eyebrow", Category: "Smileys & Emotion", Unicode: "U+1F928"},
	{Emoji: "😐", Name: "neutral_face", Category: "Smileys & Emotion", Unicode: "U+1F610"},
	{Emoji: "😑", Name: "expressionless_face", Category: "Smileys & Emotion", Unicode: "U+1F611"},
	{Emoji: "😶", Name: "face_without_mouth", Category: "Smileys & Emotion", Unicode: "U+1F636"},
	{Emoji: "😏", Name: "smirking_face", Category: "Smileys & Emotion", Unicode: "U+1F60F"},
	{Emoji: "😒", Name: "unamused_face", Category: "Smileys & Emotion", Unicode: "U+1F612"},
	{Emoji: "🙄", Name: "face_with_rolling_eyes", Category: "Smileys & Emotion", Unicode: "U+1F644"},
	{Emoji: "😬", Name: "grimacing_face", Category: "Smileys & Emotion", Unicode: "U+1F62C"},
	{Emoji: "😮", Name: "face_with_open_mouth", Category: "Smileys & Emotion", Unicode: "U+1F62E"},
	{Emoji: "🤥", Name: "lying_face", Category: "Smileys & Emotion", Unicode: "U+1F925"},
	{Emoji: "😌", Name: "relieved_face", Category: "Smileys & Emotion", Unicode: "U+1F60C"},
	{Emoji: "😔", Name: "pensive_face", Category: "Smileys & Emotion", Unicode: "U+1F614"},
	{Emoji: "😪", Name: "sleepy_face", Category: "Smileys & Emotion", Unicode: "U+1F62A"},
	{Emoji: "🤤", Name: "drooling_face", Category: "Smileys & Emotion", Unicode: "U+1F924"},
	{Emoji: "😴", Name: "sleeping_face", Category: "Smileys & Emotion", Unicode: "U+1F634"},
	{Emoji: "😷", Name: "face_with_medical_mask", Category: "Smileys & Emotion", Unicode: "U+1F637"},
	{Emoji: "🤒", Name: "face_with_thermometer", Category: "Smileys & Emotion", Unicode: "U+1F912"},
	{Emoji: "🤕", Name: "face_with_head_bandage", Category: "Smileys & Emotion", Unicode: "U+1F915"},
	{Emoji: "🤢", Name: "nauseated_face", Category: "Smileys & Emotion", Unicode: "U+1F922"},
	{Emoji: "🤧", Name: "sneezing_face", Category: "Smileys & Emotion", Unicode: "U+1F927"},
	{Emoji: "🥵", Name: "hot_face", Category: "Smileys & Emotion", Unicode: "U+1F975"},
	{Emoji: "🥶", Name: "cold_face", Category: "Smileys & Emotion", Unicode: "U+1F976"},
	{Emoji: "🥴", Name: "woozy_face", Category: "Smileys & Emotion", Unicode: "U+1F974"},
	{Emoji: "😵", Name: "face_with_crossed_out_eyes", Category: "Smileys & Emotion", Unicode: "U+1F635"},
	{Emoji: "🤯", Name: "exploding_head", Category: "Smileys & Emotion", Unicode: "U+1F92F"},
	{Emoji: "🤠", Name: "cowboy_hat_face", Category: "Smileys & Emotion", Unicode: "U+1F920"},
	{Emoji: "🥳", Name: "partying_face", Category: "Smileys & Emotion", Unicode: "U+1F973"},
	{Emoji: "🥸", Name: "disguised_face", Category: "Smileys & Emotion", Unicode: "U+1F978"},
	{Emoji: "😎", Name: "smiling_face_with_sunglasses", Category: "Smileys & Emotion", Unicode: "U+1F60E"},
	{Emoji: "🤓", Name: "nerd_face", Category: "Smileys & Emotion", Unicode: "U+1F913"},
	{Emoji: "🧐", Name: "face_with_monocle", Category: "Smileys & Emotion", Unicode: "U+1F9D0"},
	{Emoji: "😕", Name: "confused_face", Category: "Smileys & Emotion", Unicode: "U+1F615"},
	{Emoji: "😟", Name: "worried_face", Category: "Smileys & Emotion", Unicode: "U+1F61F"},
	{Emoji: "🙁", Name: "slightly_frowning_face", Category: "Smileys & Emotion", Unicode: "U+1F641"},
	{Emoji: "😯", Name: "hushed_face", Category: "Smileys & Emotion", Unicode: "U+1F62F"},
	{Emoji: "😲", Name: "astonished_face", Category: "Smileys & Emotion", Unicode: "U+1F632"},
	{Emoji: "😳", Name: "flushed_face", Category: "Smileys & Emotion", Unicode: "U+1F633"},
	{Emoji: "🥺", Name: "pleading_face", Category: "Smileys & Emotion", Unicode: "U+1F97A"},
	{Emoji: "😦", Name: "frowning_face_with_open_mouth", Category: "Smileys & Emotion", Unicode: "U+1F626"},
	{Emoji: "😧", Name: "anguished_face", Category: "Smileys & Emotion", Unicode: "U+1F627"},
	{Emoji: "😨", Name: "fearful_face", Category: "Smileys & Emotion", Unicode: "U+1F628"},
	{Emoji: "😰", Name: "anxious_face_with_sweat", Category: "Smileys & Emotion", Unicode: "U+1F630"},
	{Emoji: "😥", Name: "sad_but_relieved_face", Category: "Smileys & Emotion", Unicode: "U+1F625"},
	{Emoji: "😢", Name: "crying_face", Category: "Smileys & Emotion", Unicode: "U+1F622"},
	{Emoji: "😭", Name: "loudly_crying_face", Category: "Smileys & Emotion", Unicode: "U+1F62D"},
	{Emoji: "😱", Name: "face_screaming_in_fear", Category: "Smileys & Emotion", Unicode: "U+1F631"},
	{Emoji: "😖", Name: "confounded_face", Category: "Smileys & Emotion", Unicode: "U+1F616"},
	{Emoji: "😣", Name: "persevering_face", Category: "Smileys & Emotion", Unicode: "U+1F623"},
	{Emoji: "😞", Name: "disappointed_face", Category: "Smileys & Emotion", Unicode: "U+1F61E"},
	{Emoji: "😓", Name: "downcast_face_with_sweat", Category: "Smileys & Emotion", Unicode: "U+1F613"},
	{Emoji: "😩", Name: "weary_face", Category: "Smileys & Emotion", Unicode: "U+1F629"},
	{Emoji: "😫", Name: "tired_face", Category: "Smileys & Emotion", Unicode: "U+1F62B"},
	{Emoji: "🥱", Name: "yawning_face", Category: "Smileys & Emotion", Unicode: "U+1F971"},
	{Emoji: "😤", Name: "face_with_steam_from_nose", Category: "Smileys & Emotion", Unicode: "U+1F624"},
	{Emoji: "😡", Name: "enraged_face", Category: "Smileys & Emotion", Unicode: "U+1F621"},
	{Emoji: "😠", Name: "angry_face", Category: "Smileys & Emotion", Unicode: "U+1F620"},
	{Emoji: "🤬", Name: "face_with_symbols_on_mouth", Category: "Smileys & Emotion", Unicode: "U+1F92C"},
	{Emoji: "😈", Name: "smiling_face_with_horns", Category: "Smileys & Emotion", Unicode: "U+1F608"},
	{Emoji: "👿", Name: "angry_face_with_horns", Category: "Smileys & Emotion", Unicode: "U+1F47F"},
	{Emoji: "💀", Name: "skull", Category: "Smileys & Emotion", Unicode: "U+1F480"},
	{Emoji: "☠️", Name: "skull_and_crossbones", Category: "Smileys & Emotion", Unicode: "U+2620"},
	{Emoji: "💩", Name: "pile_of_poo", Category: "Smileys & Emotion", Unicode: "U+1F4A9"},
	{Emoji: "🤡", Name: "clown_face", Category: "Smileys & Emotion", Unicode: "U+1F921"},
	{Emoji: "👹", Name: "ogre", Category: "Smileys & Emotion", Unicode: "U+1F479"},
	{Emoji: "👺", Name: "goblin", Category: "Smileys & Emotion", Unicode: "U+1F47A"},
	{Emoji: "👻", Name: "ghost", Category: "Smileys & Emotion", Unicode: "U+1F47B"},
	{Emoji: "👽", Name: "alien", Category: "Smileys & Emotion", Unicode: "U+1F47D"},
	{Emoji: "👾", Name: "alien_monster", Category: "Smileys & Emotion", Unicode: "U+1F47E"},
	{Emoji: "🤖", Name: "robot", Category: "Smileys & Emotion", Unicode: "U+1F916"},
	{Emoji: "😺", Name: "grinning_cat", Category: "Smileys & Emotion", Unicode: "U+1F63A"},
	{Emoji: "😸", Name: "grinning_cat_with_smiling_eyes", Category: "Smileys & Emotion", Unicode: "U+1F638"},
	{Emoji: "😹", Name: "cat_with_tears_of_joy", Category: "Smileys & Emotion", Unicode: "U+1F639"},
	{Emoji: "😻", Name: "smiling_cat_with_heart_eyes", Category: "Smileys & Emotion", Unicode: "U+1F63B"},
	{Emoji: "😼", Name: "cat_with_wry_smile", Category: "Smileys & Emotion", Unicode: "U+1F63C"},
	{Emoji: "😽", Name: "kissing_cat", Category: "Smileys & Emotion", Unicode: "U+1F63D"},
	{Emoji: "🙀", Name: "weary_cat", Category: "Smileys & Emotion", Unicode: "U+1F640"},
	{Emoji: "😿", Name: "crying_cat", Category: "Smileys & Emotion", Unicode: "U+1F63F"},
	{Emoji: "😾", Name: "pouting_cat", Category: "Smileys & Emotion", Unicode: "U+1F63E"},
	{Emoji: "❤️", Name: "red_heart", Category: "Smileys & Emotion", Unicode: "U+2764"},
	{Emoji: "🧡", Name: "orange_heart", Category: "Smileys & Emotion", Unicode: "U+1F9E1"},
	{Emoji: "💛", Name: "yellow_heart", Category: "Smileys & Emotion", Unicode: "U+1F49B"},
	{Emoji: "💚", Name: "green_heart", Category: "Smileys & Emotion", Unicode: "U+1F49A"},
	{Emoji: "💙", Name: "blue_heart", Category: "Smileys & Emotion", Unicode: "U+1F499"},
	{Emoji: "💜", Name: "purple_heart", Category: "Smileys & Emotion", Unicode: "U+1F49C"},
	{Emoji: "🖤", Name: "black_heart", Category: "Smileys & Emotion", Unicode: "U+1F5A4"},
	{Emoji: "🤍", Name: "white_heart", Category: "Smileys & Emotion", Unicode: "U+1F90D"},
	{Emoji: "🤎", Name: "brown_heart", Category: "Smileys & Emotion", Unicode: "U+1F90E"},
	{Emoji: "💔", Name: "broken_heart", Category: "Smileys & Emotion", Unicode: "U+1F494"},
	{Emoji: "💕", Name: "two_hearts", Category: "Smileys & Emotion", Unicode: "U+1F495"},
	{Emoji: "💞", Name: "revolving_hearts", Category: "Smileys & Emotion", Unicode: "U+1F49E"},
	{Emoji: "💓", Name: "beating_heart", Category: "Smileys & Emotion", Unicode: "U+1F493"},
	{Emoji: "💗", Name: "growing_heart", Category: "Smileys & Emotion", Unicode: "U+1F497"},
	{Emoji: "💖", Name: "sparkling_heart", Category: "Smileys & Emotion", Unicode: "U+1F496"},
	{Emoji: "💘", Name: "heart_with_arrow", Category: "Smileys & Emotion", Unicode: "U+1F498"},
	{Emoji: "💝", Name: "heart_with_ribbon", Category: "Smileys & Emotion", Unicode: "U+1F49D"},
	{Emoji: "💟", Name: "heart_decoration", Category: "Smileys & Emotion", Unicode: "U+1F49F"},
	{Emoji: "💋", Name: "kiss_mark", Category: "Smileys & Emotion", Unicode: "U+1F48B"},
	{Emoji: "💯", Name: "hundred_points", Category: "Smileys & Emotion", Unicode: "U+1F4AF"},
	{Emoji: "💢", Name: "anger_symbol", Category: "Smileys & Emotion", Unicode: "U+1F4A2"},
	{Emoji: "💥", Name: "collision", Category: "Smileys & Emotion", Unicode: "U+1F4A5"},
	{Emoji: "💫", Name: "dizzy", Category: "Smileys & Emotion", Unicode: "U+1F4AB"},
	{Emoji: "💦", Name: "sweat_droplets", Category: "Smileys & Emotion", Unicode: "U+1F4A6"},
	{Emoji: "💨", Name: "dashing_away", Category: "Smileys & Emotion", Unicode: "U+1F4A8"},
	{Emoji: "🕳️", Name: "hole", Category: "Smileys & Emotion", Unicode: "U+1F573"},
	{Emoji: "💬", Name: "speech_balloon", Category: "Smileys & Emotion", Unicode: "U+1F4AC"},
	{Emoji: "💭", Name: "thought_balloon", Category: "Smileys & Emotion", Unicode: "U+1F4AD"},
	{Emoji: "💤", Name: "zzz", Category: "Smileys & Emotion", Unicode: "U+1F4A4"},

	// People & Body
	{Emoji: "👋", Name: "waving_hand", Category: "People & Body", Unicode: "U+1F44B"},
	{Emoji: "🤚", Name: "raised_back_of_hand", Category: "People & Body", Unicode: "U+1F91A"},
	{Emoji: "🖐️", Name: "hand_with_fingers_splayed", Category: "People & Body", Unicode: "U+1F590"},
	{Emoji: "✋", Name: "raised_hand", Category: "People & Body", Unicode: "U+270B"},
	{Emoji: "🖖", Name: "vulcan_salute", Category: "People & Body", Unicode: "U+1F596"},
	{Emoji: "👌", Name: "ok_hand", Category: "People & Body", Unicode: "U+1F44C"},
	{Emoji: "🤌", Name: "pinched_fingers", Category: "People & Body", Unicode: "U+1F90C"},
	{Emoji: "✌️", Name: "victory_hand", Category: "People & Body", Unicode: "U+270C"},
	{Emoji: "🤞", Name: "crossed_fingers", Category: "People & Body", Unicode: "U+1F91E"},
	{Emoji: "🤟", Name: "love_you_gesture", Category: "People & Body", Unicode: "U+1F91F"},
	{Emoji: "🤘", Name: "sign_of_the_horns", Category: "People & Body", Unicode: "U+1F918"},
	{Emoji: "🤙", Name: "call_me_hand", Category: "People & Body", Unicode: "U+1F919"},
	{Emoji: "👈", Name: "backhand_index_pointing_left", Category: "People & Body", Unicode: "U+1F448"},
	{Emoji: "👉", Name: "backhand_index_pointing_right", Category: "People & Body", Unicode: "U+1F449"},
	{Emoji: "👆", Name: "backhand_index_pointing_up", Category: "People & Body", Unicode: "U+1F446"},
	{Emoji: "🖕", Name: "middle_finger", Category: "People & Body", Unicode: "U+1F595"},
	{Emoji: "👇", Name: "backhand_index_pointing_down", Category: "People & Body", Unicode: "U+1F447"},
	{Emoji: "☝️", Name: "index_pointing_up", Category: "People & Body", Unicode: "U+261D"},
	{Emoji: "👍", Name: "thumbs_up", Category: "People & Body", Unicode: "U+1F44D"},
	{Emoji: "👎", Name: "thumbs_down", Category: "People & Body", Unicode: "U+1F44E"},
	{Emoji: "✊", Name: "raised_fist", Category: "People & Body", Unicode: "U+270A"},
	{Emoji: "👊", Name: "oncoming_fist", Category: "People & Body", Unicode: "U+1F44A"},
	{Emoji: "🤛", Name: "left_facing_fist", Category: "People & Body", Unicode: "U+1F91B"},
	{Emoji: "🤜", Name: "right_facing_fist", Category: "People & Body", Unicode: "U+1F91C"},
	{Emoji: "👏", Name: "clapping_hands", Category: "People & Body", Unicode: "U+1F44F"},
	{Emoji: "🙌", Name: "raising_hands", Category: "People & Body", Unicode: "U+1F64C"},
	{Emoji: "👐", Name: "open_hands", Category: "People & Body", Unicode: "U+1F450"},
	{Emoji: "🤲", Name: "palms_up_together", Category: "People & Body", Unicode: "U+1F932"},
	{Emoji: "🤝", Name: "handshake", Category: "People & Body", Unicode: "U+1F91D"},
	{Emoji: "🙏", Name: "folded_hands", Category: "People & Body", Unicode: "U+1F64F"},
	{Emoji: "✍️", Name: "writing_hand", Category: "People & Body", Unicode: "U+270D"},
	{Emoji: "💪", Name: "flexed_biceps", Category: "People & Body", Unicode: "U+1F4AA"},
	{Emoji: "🦾", Name: "mechanical_arm", Category: "People & Body", Unicode: "U+1F9BE"},
	{Emoji: "🦵", Name: "leg", Category: "People & Body", Unicode: "U+1F9B5"},
	{Emoji: "🦶", Name: "foot", Category: "People & Body", Unicode: "U+1F9B6"},
	{Emoji: "👂", Name: "ear", Category: "People & Body", Unicode: "U+1F442"},
	{Emoji: "🦻", Name: "ear_with_hearing_aid", Category: "People & Body", Unicode: "U+1F9BB"},
	{Emoji: "👃", Name: "nose", Category: "People & Body", Unicode: "U+1F443"},
	{Emoji: "🧠", Name: "brain", Category: "People & Body", Unicode: "U+1F9E0"},
	{Emoji: "🫀", Name: "anatomical_heart", Category: "People & Body", Unicode: "U+1FAC0"},
	{Emoji: "🫁", Name: "lungs", Category: "People & Body", Unicode: "U+1FAC1"},
	{Emoji: "🦷", Name: "tooth", Category: "People & Body", Unicode: "U+1F9B7"},
	{Emoji: "🦴", Name: "bone", Category: "People & Body", Unicode: "U+1F9B4"},
	{Emoji: "👀", Name: "eyes", Category: "People & Body", Unicode: "U+1F440"},
	{Emoji: "👁️", Name: "eye", Category: "People & Body", Unicode: "U+1F441"},
	{Emoji: "👅", Name: "tongue", Category: "People & Body", Unicode: "U+1F445"},
	{Emoji: "👄", Name: "mouth", Category: "People & Body", Unicode: "U+1F444"},
	{Emoji: "🫦", Name: "biting_lip", Category: "People & Body", Unicode: "U+1FAB6"},
	{Emoji: "👶", Name: "baby", Category: "People & Body", Unicode: "U+1F476"},
	{Emoji: "🧒", Name: "child", Category: "People & Body", Unicode: "U+1F9D2"},
	{Emoji: "👦", Name: "boy", Category: "People & Body", Unicode: "U+1F466"},
	{Emoji: "👧", Name: "girl", Category: "People & Body", Unicode: "U+1F467"},
	{Emoji: "🧑", Name: "person", Category: "People & Body", Unicode: "U+1F9D1"},
	{Emoji: "👱", Name: "person_blond_hair", Category: "People & Body", Unicode: "U+1F471"},
	{Emoji: "👨", Name: "man", Category: "People & Body", Unicode: "U+1F468"},
	{Emoji: "🧔", Name: "person_beard", Category: "People & Body", Unicode: "U+1F9D4"},
	{Emoji: "👩", Name: "woman", Category: "People & Body", Unicode: "U+1F469"},
	{Emoji: "🧓", Name: "older_person", Category: "People & Body", Unicode: "U+1F9D3"},
	{Emoji: "👴", Name: "old_man", Category: "People & Body", Unicode: "U+1F474"},
	{Emoji: "👵", Name: "old_woman", Category: "People & Body", Unicode: "U+1F475"},
	{Emoji: "🙍", Name: "person_frowning", Category: "People & Body", Unicode: "U+1F64D"},
	{Emoji: "🙎", Name: "person_pouting", Category: "People & Body", Unicode: "U+1F64E"},
	{Emoji: "🙅", Name: "person_gesturing_no", Category: "People & Body", Unicode: "U+1F645"},
	{Emoji: "🙆", Name: "person_gesturing_ok", Category: "People & Body", Unicode: "U+1F646"},
	{Emoji: "💁", Name: "person_tipping_hand", Category: "People & Body", Unicode: "U+1F481"},
	{Emoji: "🙋", Name: "person_raising_hand", Category: "People & Body", Unicode: "U+1F64B"},
	{Emoji: "🧏", Name: "deaf_person", Category: "People & Body", Unicode: "U+1F9CF"},
	{Emoji: "🙇", Name: "person_bowing", Category: "People & Body", Unicode: "U+1F647"},
	{Emoji: "🤦", Name: "person_facepalming", Category: "People & Body", Unicode: "U+1F926"},
	{Emoji: "🤷", Name: "person_shrugging", Category: "People & Body", Unicode: "U+1F937"},

	// Animals & Nature
	{Emoji: "🐶", Name: "dog_face", Category: "Animals & Nature", Unicode: "U+1F436"},
	{Emoji: "🐱", Name: "cat_face", Category: "Animals & Nature", Unicode: "U+1F431"},
	{Emoji: "🐭", Name: "mouse_face", Category: "Animals & Nature", Unicode: "U+1F42D"},
	{Emoji: "🐹", Name: "hamster", Category: "Animals & Nature", Unicode: "U+1F439"},
	{Emoji: "🐰", Name: "rabbit_face", Category: "Animals & Nature", Unicode: "U+1F430"},
	{Emoji: "🦊", Name: "fox", Category: "Animals & Nature", Unicode: "U+1F98A"},
	{Emoji: "🐻", Name: "bear", Category: "Animals & Nature", Unicode: "U+1F43B"},
	{Emoji: "🐼", Name: "panda", Category: "Animals & Nature", Unicode: "U+1F43C"},
	{Emoji: "🐨", Name: "koala", Category: "Animals & Nature", Unicode: "U+1F428"},
	{Emoji: "🐯", Name: "tiger_face", Category: "Animals & Nature", Unicode: "U+1F42F"},
	{Emoji: "🦁", Name: "lion", Category: "Animals & Nature", Unicode: "U+1F981"},
	{Emoji: "🐮", Name: "cow_face", Category: "Animals & Nature", Unicode: "U+1F42E"},
	{Emoji: "🐷", Name: "pig_face", Category: "Animals & Nature", Unicode: "U+1F437"},
	{Emoji: "🐸", Name: "frog", Category: "Animals & Nature", Unicode: "U+1F438"},
	{Emoji: "🐵", Name: "monkey_face", Category: "Animals & Nature", Unicode: "U+1F435"},
	{Emoji: "🙈", Name: "see_no_evil_monkey", Category: "Animals & Nature", Unicode: "U+1F648"},
	{Emoji: "🙉", Name: "hear_no_evil_monkey", Category: "Animals & Nature", Unicode: "U+1F649"},
	{Emoji: "🙊", Name: "speak_no_evil_monkey", Category: "Animals & Nature", Unicode: "U+1F64A"},
	{Emoji: "🐔", Name: "chicken", Category: "Animals & Nature", Unicode: "U+1F414"},
	{Emoji: "🐧", Name: "penguin", Category: "Animals & Nature", Unicode: "U+1F427"},
	{Emoji: "🐦", Name: "bird", Category: "Animals & Nature", Unicode: "U+1F426"},
	{Emoji: "🐤", Name: "baby_chick", Category: "Animals & Nature", Unicode: "U+1F424"},
	{Emoji: "🦆", Name: "duck", Category: "Animals & Nature", Unicode: "U+1F986"},
	{Emoji: "🦅", Name: "eagle", Category: "Animals & Nature", Unicode: "U+1F985"},
	{Emoji: "🦉", Name: "owl", Category: "Animals & Nature", Unicode: "U+1F989"},
	{Emoji: "🦇", Name: "bat", Category: "Animals & Nature", Unicode: "U+1F987"},
	{Emoji: "🐺", Name: "wolf", Category: "Animals & Nature", Unicode: "U+1F43A"},
	{Emoji: "🐗", Name: "boar", Category: "Animals & Nature", Unicode: "U+1F417"},
	{Emoji: "🐴", Name: "horse_face", Category: "Animals & Nature", Unicode: "U+1F434"},
	{Emoji: "🦄", Name: "unicorn", Category: "Animals & Nature", Unicode: "U+1F984"},
	{Emoji: "🐝", Name: "honeybee", Category: "Animals & Nature", Unicode: "U+1F41D"},
	{Emoji: "🐛", Name: "bug", Category: "Animals & Nature", Unicode: "U+1F41B"},
	{Emoji: "🦋", Name: "butterfly", Category: "Animals & Nature", Unicode: "U+1F98B"},
	{Emoji: "🐌", Name: "snail", Category: "Animals & Nature", Unicode: "U+1F40C"},
	{Emoji: "🐞", Name: "lady_beetle", Category: "Animals & Nature", Unicode: "U+1F41E"},
	{Emoji: "🐜", Name: "ant", Category: "Animals & Nature", Unicode: "U+1F41C"},
	{Emoji: "🪲", Name: "beetle", Category: "Animals & Nature", Unicode: "U+1FAB2"},
	{Emoji: "🦟", Name: "mosquito", Category: "Animals & Nature", Unicode: "U+1F99F"},
	{Emoji: "🦗", Name: "cricket", Category: "Animals & Nature", Unicode: "U+1F997"},
	{Emoji: "🪳", Name: "cockroach", Category: "Animals & Nature", Unicode: "U+1FAB3"},
	{Emoji: "🕷️", Name: "spider", Category: "Animals & Nature", Unicode: "U+1F577"},
	{Emoji: "🦂", Name: "scorpion", Category: "Animals & Nature", Unicode: "U+1F982"},
	{Emoji: "🐢", Name: "turtle", Category: "Animals & Nature", Unicode: "U+1F422"},
	{Emoji: "🐍", Name: "snake", Category: "Animals & Nature", Unicode: "U+1F40D"},
	{Emoji: "🦎", Name: "lizard", Category: "Animals & Nature", Unicode: "U+1F98E"},
	{Emoji: "🦖", Name: "t_rex", Category: "Animals & Nature", Unicode: "U+1F996"},
	{Emoji: "🦕", Name: "sauropod", Category: "Animals & Nature", Unicode: "U+1F995"},
	{Emoji: "🐊", Name: "crocodile", Category: "Animals & Nature", Unicode: "U+1F40A"},
	{Emoji: "🐉", Name: "dragon", Category: "Animals & Nature", Unicode: "U+1F409"},
	{Emoji: "🐲", Name: "dragon_face", Category: "Animals & Nature", Unicode: "U+1F432"},
	{Emoji: "🌵", Name: "cactus", Category: "Animals & Nature", Unicode: "U+1F335"},
	{Emoji: "🎄", Name: "christmas_tree", Category: "Animals & Nature", Unicode: "U+1F384"},
	{Emoji: "🌲", Name: "evergreen_tree", Category: "Animals & Nature", Unicode: "U+1F332"},
	{Emoji: "🌳", Name: "deciduous_tree", Category: "Animals & Nature", Unicode: "U+1F333"},
	{Emoji: "🌴", Name: "palm_tree", Category: "Animals & Nature", Unicode: "U+1F334"},
	{Emoji: "🌱", Name: "seedling", Category: "Animals & Nature", Unicode: "U+1F331"},
	{Emoji: "🌿", Name: "herb", Category: "Animals & Nature", Unicode: "U+1F33F"},
	{Emoji: "☘️", Name: "shamrock", Category: "Animals & Nature", Unicode: "U+2618"},
	{Emoji: "🍀", Name: "four_leaf_clover", Category: "Animals & Nature", Unicode: "U+1F340"},
	{Emoji: "🎋", Name: "tanabata_tree", Category: "Animals & Nature", Unicode: "U+1F38B"},
	{Emoji: "🎍", Name: "pine_decoration", Category: "Animals & Nature", Unicode: "U+1F38D"},
	{Emoji: "🍃", Name: "leaf_fluttering_in_wind", Category: "Animals & Nature", Unicode: "U+1F343"},
	{Emoji: "🍂", Name: "fallen_leaf", Category: "Animals & Nature", Unicode: "U+1F342"},
	{Emoji: "🍁", Name: "maple_leaf", Category: "Animals & Nature", Unicode: "U+1F341"},
	{Emoji: "🌾", Name: "sheaf_of_rice", Category: "Animals & Nature", Unicode: "U+1F33E"},
	{Emoji: "🌺", Name: "hibiscus", Category: "Animals & Nature", Unicode: "U+1F33A"},
	{Emoji: "🌻", Name: "sunflower", Category: "Animals & Nature", Unicode: "U+1F33B"},
	{Emoji: "🌹", Name: "rose", Category: "Animals & Nature", Unicode: "U+1F339"},
	{Emoji: "🥀", Name: "wilted_flower", Category: "Animals & Nature", Unicode: "U+1F940"},
	{Emoji: "🌷", Name: "tulip", Category: "Animals & Nature", Unicode: "U+1F337"},
	{Emoji: "🌸", Name: "cherry_blossom", Category: "Animals & Nature", Unicode: "U+1F338"},
	{Emoji: "💐", Name: "bouquet", Category: "Animals & Nature", Unicode: "U+1F490"},
	{Emoji: "🍄", Name: "mushroom", Category: "Animals & Nature", Unicode: "U+1F344"},
	{Emoji: "🐚", Name: "spiral_shell", Category: "Animals & Nature", Unicode: "U+1F41A"},
	{Emoji: "🪸", Name: "coral", Category: "Animals & Nature", Unicode: "U+1FAB8"},
	{Emoji: "🪨", Name: "rock", Category: "Animals & Nature", Unicode: "U+1FAA8"},
	{Emoji: "🪵", Name: "wood", Category: "Animals & Nature", Unicode: "U+1FAB5"},

	// Food & Drink
	{Emoji: "🍇", Name: "grapes", Category: "Food & Drink", Unicode: "U+1F347"},
	{Emoji: "🍈", Name: "melon", Category: "Food & Drink", Unicode: "U+1F348"},
	{Emoji: "🍉", Name: "watermelon", Category: "Food & Drink", Unicode: "U+1F349"},
	{Emoji: "🍊", Name: "tangerine", Category: "Food & Drink", Unicode: "U+1F34A"},
	{Emoji: "🍋", Name: "lemon", Category: "Food & Drink", Unicode: "U+1F34B"},
	{Emoji: "🍌", Name: "banana", Category: "Food & Drink", Unicode: "U+1F34C"},
	{Emoji: "🍍", Name: "pineapple", Category: "Food & Drink", Unicode: "U+1F34D"},
	{Emoji: "🥭", Name: "mango", Category: "Food & Drink", Unicode: "U+1F96D"},
	{Emoji: "🍎", Name: "red_apple", Category: "Food & Drink", Unicode: "U+1F34E"},
	{Emoji: "🍏", Name: "green_apple", Category: "Food & Drink", Unicode: "U+1F34F"},
	{Emoji: "🍐", Name: "pear", Category: "Food & Drink", Unicode: "U+1F350"},
	{Emoji: "🍑", Name: "peach", Category: "Food & Drink", Unicode: "U+1F351"},
	{Emoji: "🍒", Name: "cherries", Category: "Food & Drink", Unicode: "U+1F352"},
	{Emoji: "🍓", Name: "strawberry", Category: "Food & Drink", Unicode: "U+1F353"},
	{Emoji: "🫐", Name: "blueberries", Category: "Food & Drink", Unicode: "U+1FAD0"},
	{Emoji: "🥝", Name: "kiwi_fruit", Category: "Food & Drink", Unicode: "U+1F95D"},
	{Emoji: "🍅", Name: "tomato", Category: "Food & Drink", Unicode: "U+1F345"},
	{Emoji: "🫒", Name: "olive", Category: "Food & Drink", Unicode: "U+1FAD2"},
	{Emoji: "🥥", Name: "coconut", Category: "Food & Drink", Unicode: "U+1F965"},
	{Emoji: "🥑", Name: "avocado", Category: "Food & Drink", Unicode: "U+1F951"},
	{Emoji: "🍆", Name: "eggplant", Category: "Food & Drink", Unicode: "U+1F346"},
	{Emoji: "🥔", Name: "potato", Category: "Food & Drink", Unicode: "U+1F954"},
	{Emoji: "🥕", Name: "carrot", Category: "Food & Drink", Unicode: "U+1F955"},
	{Emoji: "🌽", Name: "ear_of_corn", Category: "Food & Drink", Unicode: "U+1F33D"},
	{Emoji: "🌶️", Name: "hot_pepper", Category: "Food & Drink", Unicode: "U+1F336"},
	{Emoji: "🫑", Name: "bell_pepper", Category: "Food & Drink", Unicode: "U+1FAD1"},
	{Emoji: "🥒", Name: "cucumber", Category: "Food & Drink", Unicode: "U+1F952"},
	{Emoji: "🥬", Name: "leafy_green", Category: "Food & Drink", Unicode: "U+1F96C"},
	{Emoji: "🥦", Name: "broccoli", Category: "Food & Drink", Unicode: "U+1F966"},
	{Emoji: "🧄", Name: "garlic", Category: "Food & Drink", Unicode: "U+1F9C4"},
	{Emoji: "🧅", Name: "onion", Category: "Food & Drink", Unicode: "U+1F9C5"},
	{Emoji: "🥜", Name: "peanuts", Category: "Food & Drink", Unicode: "U+1F95C"},
	{Emoji: "🌰", Name: "chestnut", Category: "Food & Drink", Unicode: "U+1F330"},
	{Emoji: "🍞", Name: "bread", Category: "Food & Drink", Unicode: "U+1F35E"},
	{Emoji: "🥐", Name: "croissant", Category: "Food & Drink", Unicode: "U+1F950"},
	{Emoji: "🥖", Name: "baguette_bread", Category: "Food & Drink", Unicode: "U+1F956"},
	{Emoji: "🫓", Name: "flatbread", Category: "Food & Drink", Unicode: "U+1FAD3"},
	{Emoji: "🥨", Name: "pretzel", Category: "Food & Drink", Unicode: "U+1F968"},
	{Emoji: "🥯", Name: "bagel", Category: "Food & Drink", Unicode: "U+1F96F"},
	{Emoji: "🧀", Name: "cheese_wedge", Category: "Food & Drink", Unicode: "U+1F9C0"},
	{Emoji: "🍖", Name: "meat_on_bone", Category: "Food & Drink", Unicode: "U+1F356"},
	{Emoji: "🍗", Name: "poultry_leg", Category: "Food & Drink", Unicode: "U+1F357"},
	{Emoji: "🥩", Name: "cut_of_meat", Category: "Food & Drink", Unicode: "U+1F969"},
	{Emoji: "🥓", Name: "bacon", Category: "Food & Drink", Unicode: "U+1F953"},
	{Emoji: "🌮", Name: "taco", Category: "Food & Drink", Unicode: "U+1F32E"},
	{Emoji: "🌯", Name: "burrito", Category: "Food & Drink", Unicode: "U+1F32F"},
	{Emoji: "🥙", Name: "stuffed_flatbread", Category: "Food & Drink", Unicode: "U+1F959"},
	{Emoji: "🧆", Name: "falafel", Category: "Food & Drink", Unicode: "U+1F9C6"},
	{Emoji: "🥚", Name: "egg", Category: "Food & Drink", Unicode: "U+1F95A"},
	{Emoji: "🍳", Name: "cooking", Category: "Food & Drink", Unicode: "U+1F373"},
	{Emoji: "🥘", Name: "shallow_pan_of_food", Category: "Food & Drink", Unicode: "U+1F958"},
	{Emoji: "🍲", Name: "pot_of_food", Category: "Food & Drink", Unicode: "U+1F372"},
	{Emoji: "🫕", Name: "fondue", Category: "Food & Drink", Unicode: "U+1FAD5"},
	{Emoji: "🍜", Name: "steaming_bowl", Category: "Food & Drink", Unicode: "U+1F35C"},
	{Emoji: "🍝", Name: "spaghetti", Category: "Food & Drink", Unicode: "U+1F35D"},
	{Emoji: "🍠", Name: "roasted_sweet_potato", Category: "Food & Drink", Unicode: "U+1F360"},
	{Emoji: "🍢", Name: "oden", Category: "Food & Drink", Unicode: "U+1F362"},
	{Emoji: "🍣", Name: "sushi", Category: "Food & Drink", Unicode: "U+1F363"},
	{Emoji: "🍤", Name: "fried_shrimp", Category: "Food & Drink", Unicode: "U+1F364"},
	{Emoji: "🍙", Name: "rice_ball", Category: "Food & Drink", Unicode: "U+1F359"},
	{Emoji: "🍚", Name: "cooked_rice", Category: "Food & Drink", Unicode: "U+1F35A"},
	{Emoji: "🍛", Name: "curry_rice", Category: "Food & Drink", Unicode: "U+1F35B"},
	{Emoji: "🍱", Name: "bento_box", Category: "Food & Drink", Unicode: "U+1F371"},
	{Emoji: "🥟", Name: "dumpling", Category: "Food & Drink", Unicode: "U+1F95F"},
	{Emoji: "🍦", Name: "soft_ice_cream", Category: "Food & Drink", Unicode: "U+1F366"},
	{Emoji: "🍧", Name: "shaved_ice", Category: "Food & Drink", Unicode: "U+1F367"},
	{Emoji: "🍨", Name: "ice_cream", Category: "Food & Drink", Unicode: "U+1F368"},
	{Emoji: "🍩", Name: "doughnut", Category: "Food & Drink", Unicode: "U+1F369"},
	{Emoji: "🍪", Name: "cookie", Category: "Food & Drink", Unicode: "U+1F36A"},
	{Emoji: "🎂", Name: "birthday_cake", Category: "Food & Drink", Unicode: "U+1F382"},
	{Emoji: "🍰", Name: "shortcake", Category: "Food & Drink", Unicode: "U+1F370"},
	{Emoji: "🧁", Name: "cupcake", Category: "Food & Drink", Unicode: "U+1F9C1"},
	{Emoji: "🥧", Name: "pie", Category: "Food & Drink", Unicode: "U+1F967"},
	{Emoji: "🍫", Name: "chocolate_bar", Category: "Food & Drink", Unicode: "U+1F36B"},
	{Emoji: "🍬", Name: "candy", Category: "Food & Drink", Unicode: "U+1F36C"},
	{Emoji: "🍭", Name: "lollipop", Category: "Food & Drink", Unicode: "U+1F36D"},
	{Emoji: "🍮", Name: "custard", Category: "Food & Drink", Unicode: "U+1F36E"},
	{Emoji: "🍯", Name: "honey_pot", Category: "Food & Drink", Unicode: "U+1F36F"},
	{Emoji: "🍼", Name: "baby_bottle", Category: "Food & Drink", Unicode: "U+1F37C"},
	{Emoji: "🥛", Name: "glass_of_milk", Category: "Food & Drink", Unicode: "U+1F95B"},
	{Emoji: "☕", Name: "hot_beverage", Category: "Food & Drink", Unicode: "U+2615"},
	{Emoji: "🫖", Name: "teapot", Category: "Food & Drink", Unicode: "U+1FAD6"},
	{Emoji: "🍵", Name: "teacup_without_handle", Category: "Food & Drink", Unicode: "U+1F375"},
	{Emoji: "🧃", Name: "beverage_box", Category: "Food & Drink", Unicode: "U+1F9C3"},
	{Emoji: "🥤", Name: "cup_with_straw", Category: "Food & Drink", Unicode: "U+1F964"},
	{Emoji: "🧋", Name: "bubble_tea", Category: "Food & Drink", Unicode: "U+1F9CB"},
	{Emoji: "🍺", Name: "beer_mug", Category: "Food & Drink", Unicode: "U+1F37A"},
	{Emoji: "🍻", Name: "clinking_beer_mugs", Category: "Food & Drink", Unicode: "U+1F37B"},
	{Emoji: "🥂", Name: "clinking_glasses", Category: "Food & Drink", Unicode: "U+1F942"},
	{Emoji: "🍷", Name: "wine_glass", Category: "Food & Drink", Unicode: "U+1F377"},
	{Emoji: "🥃", Name: "tumbler_glass", Category: "Food & Drink", Unicode: "U+1F943"},
	{Emoji: "🍸", Name: "cocktail_glass", Category: "Food & Drink", Unicode: "U+1F378"},
	{Emoji: "🍹", Name: "tropical_drink", Category: "Food & Drink", Unicode: "U+1F379"},
	{Emoji: "🧉", Name: "mate", Category: "Food & Drink", Unicode: "U+1F9C9"},
	{Emoji: "🍾", Name: "bottle_with_popping_cork", Category: "Food & Drink", Unicode: "U+1F37E"},
	{Emoji: "🧊", Name: "ice", Category: "Food & Drink", Unicode: "U+1F9CA"},
	{Emoji: "🥄", Name: "spoon", Category: "Food & Drink", Unicode: "U+1F944"},
	{Emoji: "🍴", Name: "fork_and_knife", Category: "Food & Drink", Unicode: "U+1F374"},
	{Emoji: "🍽️", Name: "fork_and_knife_with_plate", Category: "Food & Drink", Unicode: "U+1F37D"},
	{Emoji: "🥢", Name: "chopsticks", Category: "Food & Drink", Unicode: "U+1F962"},
	{Emoji: "🧂", Name: "salt", Category: "Food & Drink", Unicode: "U+1F9C2"},
	{Emoji: "🍿", Name: "popcorn", Category: "Food & Drink", Unicode: "U+1F37F"},
	{Emoji: "🥫", Name: "canned_food", Category: "Food & Drink", Unicode: "U+1F96B"},
	{Emoji: "🍔", Name: "hamburger", Category: "Food & Drink", Unicode: "U+1F354"},
	{Emoji: "🍟", Name: "french_fries", Category: "Food & Drink", Unicode: "U+1F35F"},
	{Emoji: "🍕", Name: "pizza", Category: "Food & Drink", Unicode: "U+1F355"},
	{Emoji: "🌭", Name: "hot_dog", Category: "Food & Drink", Unicode: "U+1F32D"},

	// Travel & Places
	{Emoji: "🚗", Name: "automobile", Category: "Travel & Places", Unicode: "U+1F697"},
	{Emoji: "🚕", Name: "taxi", Category: "Travel & Places", Unicode: "U+1F695"},
	{Emoji: "🚙", Name: "sport_utility_vehicle", Category: "Travel & Places", Unicode: "U+1F699"},
	{Emoji: "🚌", Name: "bus", Category: "Travel & Places", Unicode: "U+1F68C"},
	{Emoji: "🚎", Name: "trolleybus", Category: "Travel & Places", Unicode: "U+1F68E"},
	{Emoji: "🏎️", Name: "racing_car", Category: "Travel & Places", Unicode: "U+1F3CE"},
	{Emoji: "🚓", Name: "police_car", Category: "Travel & Places", Unicode: "U+1F693"},
	{Emoji: "🚑", Name: "ambulance", Category: "Travel & Places", Unicode: "U+1F691"},
	{Emoji: "🚒", Name: "fire_engine", Category: "Travel & Places", Unicode: "U+1F692"},
	{Emoji: "🚐", Name: "minibus", Category: "Travel & Places", Unicode: "U+1F690"},
	{Emoji: "🚚", Name: "delivery_truck", Category: "Travel & Places", Unicode: "U+1F69A"},
	{Emoji: "🚛", Name: "articulated_lorry", Category: "Travel & Places", Unicode: "U+1F69B"},
	{Emoji: "🚜", Name: "tractor", Category: "Travel & Places", Unicode: "U+1F69C"},
	{Emoji: "🏍️", Name: "motorcycle", Category: "Travel & Places", Unicode: "U+1F3CD"},
	{Emoji: "🛵", Name: "motor_scooter", Category: "Travel & Places", Unicode: "U+1F6F5"},
	{Emoji: "🚲", Name: "bicycle", Category: "Travel & Places", Unicode: "U+1F6B2"},
	{Emoji: "🛴", Name: "kick_scooter", Category: "Travel & Places", Unicode: "U+1F6F4"},
	{Emoji: "✈️", Name: "airplane", Category: "Travel & Places", Unicode: "U+2708"},
	{Emoji: "🚀", Name: "rocket", Category: "Travel & Places", Unicode: "U+1F680"},
	{Emoji: "🛸", Name: "flying_saucer", Category: "Travel & Places", Unicode: "U+1F6F8"},
	{Emoji: "🚂", Name: "locomotive", Category: "Travel & Places", Unicode: "U+1F682"},
	{Emoji: "🚢", Name: "ship", Category: "Travel & Places", Unicode: "U+1F6A2"},
	{Emoji: "⛵", Name: "sailboat", Category: "Travel & Places", Unicode: "U+26F5"},
	{Emoji: "🏠", Name: "house", Category: "Travel & Places", Unicode: "U+1F3E0"},
	{Emoji: "🏡", Name: "house_with_garden", Category: "Travel & Places", Unicode: "U+1F3E1"},
	{Emoji: "🏢", Name: "office_building", Category: "Travel & Places", Unicode: "U+1F3E2"},
	{Emoji: "🏰", Name: "castle", Category: "Travel & Places", Unicode: "U+1F3F0"},
	{Emoji: "🗼", Name: "tokyo_tower", Category: "Travel & Places", Unicode: "U+1F5FC"},
	{Emoji: "🗽", Name: "statue_of_liberty", Category: "Travel & Places", Unicode: "U+1F5FD"},
	{Emoji: "⛩️", Name: "shinto_shrine", Category: "Travel & Places", Unicode: "U+26E9"},
	{Emoji: "🌋", Name: "volcano", Category: "Travel & Places", Unicode: "U+1F30B"},
	{Emoji: "🏔️", Name: "snow_capped_mountain", Category: "Travel & Places", Unicode: "U+1F3D4"},
	{Emoji: "⛰️", Name: "mountain", Category: "Travel & Places", Unicode: "U+26F0"},
	{Emoji: "🗻", Name: "mount_fuji", Category: "Travel & Places", Unicode: "U+1F5FB"},
	{Emoji: "🏕️", Name: "camping", Category: "Travel & Places", Unicode: "U+1F3D5"},
	{Emoji: "🏖️", Name: "beach_with_umbrella", Category: "Travel & Places", Unicode: "U+1F3D6"},
	{Emoji: "🏜️", Name: "desert", Category: "Travel & Places", Unicode: "U+1F3DC"},
	{Emoji: "🏝️", Name: "desert_island", Category: "Travel & Places", Unicode: "U+1F3DD"},
	{Emoji: "🏞️", Name: "national_park", Category: "Travel & Places", Unicode: "U+1F3DE"},
	{Emoji: "🌍", Name: "globe_showing_europe_africa", Category: "Travel & Places", Unicode: "U+1F30D"},
	{Emoji: "🌎", Name: "globe_showing_americas", Category: "Travel & Places", Unicode: "U+1F30E"},
	{Emoji: "🌏", Name: "globe_showing_asia_australia", Category: "Travel & Places", Unicode: "U+1F30F"},
	{Emoji: "🌐", Name: "globe_with_meridians", Category: "Travel & Places", Unicode: "U+1F310"},
	{Emoji: "🗺️", Name: "world_map", Category: "Travel & Places", Unicode: "U+1F5FA"},
	{Emoji: "🧭", Name: "compass", Category: "Travel & Places", Unicode: "U+1F9ED"},
	{Emoji: "☀️", Name: "sun", Category: "Travel & Places", Unicode: "U+2600"},
	{Emoji: "🌤️", Name: "sun_behind_small_cloud", Category: "Travel & Places", Unicode: "U+1F324"},
	{Emoji: "⛅", Name: "sun_behind_cloud", Category: "Travel & Places", Unicode: "U+26C5"},
	{Emoji: "🌦️", Name: "sun_behind_rain_cloud", Category: "Travel & Places", Unicode: "U+1F326"},
	{Emoji: "🌧️", Name: "cloud_with_rain", Category: "Travel & Places", Unicode: "U+1F327"},
	{Emoji: "⛈️", Name: "cloud_with_lightning_and_rain", Category: "Travel & Places", Unicode: "U+26C8"},
	{Emoji: "🌩️", Name: "cloud_with_lightning", Category: "Travel & Places", Unicode: "U+1F329"},
	{Emoji: "🌨️", Name: "cloud_with_snow", Category: "Travel & Places", Unicode: "U+1F328"},
	{Emoji: "❄️", Name: "snowflake", Category: "Travel & Places", Unicode: "U+2744"},
	{Emoji: "☃️", Name: "snowman", Category: "Travel & Places", Unicode: "U+2603"},
	{Emoji: "🌪️", Name: "tornado", Category: "Travel & Places", Unicode: "U+1F32A"},
	{Emoji: "🌈", Name: "rainbow", Category: "Travel & Places", Unicode: "U+1F308"},
	{Emoji: "☔", Name: "umbrella_with_rain_drops", Category: "Travel & Places", Unicode: "U+2614"},
	{Emoji: "⚡", Name: "high_voltage", Category: "Travel & Places", Unicode: "U+26A1"},
	{Emoji: "🌙", Name: "crescent_moon", Category: "Travel & Places", Unicode: "U+1F319"},
	{Emoji: "⭐", Name: "star", Category: "Travel & Places", Unicode: "U+2B50"},
	{Emoji: "🌟", Name: "glowing_star", Category: "Travel & Places", Unicode: "U+1F31F"},
	{Emoji: "🌠", Name: "shooting_star", Category: "Travel & Places", Unicode: "U+1F320"},
	{Emoji: "🌌", Name: "milky_way", Category: "Travel & Places", Unicode: "U+1F30C"},
	{Emoji: "🌑", Name: "new_moon", Category: "Travel & Places", Unicode: "U+1F311"},
	{Emoji: "🌕", Name: "full_moon", Category: "Travel & Places", Unicode: "U+1F315"},
	{Emoji: "🌞", Name: "sun_with_face", Category: "Travel & Places", Unicode: "U+1F31E"},
	{Emoji: "🌛", Name: "first_quarter_moon_face", Category: "Travel & Places", Unicode: "U+1F31B"},

	// Activities
	{Emoji: "⚽", Name: "soccer_ball", Category: "Activities", Unicode: "U+26BD"},
	{Emoji: "🏀", Name: "basketball", Category: "Activities", Unicode: "U+1F3C0"},
	{Emoji: "🏈", Name: "american_football", Category: "Activities", Unicode: "U+1F3C8"},
	{Emoji: "⚾", Name: "baseball", Category: "Activities", Unicode: "U+26BE"},
	{Emoji: "🥎", Name: "softball", Category: "Activities", Unicode: "U+1F94E"},
	{Emoji: "🎾", Name: "tennis", Category: "Activities", Unicode: "U+1F3BE"},
	{Emoji: "🏐", Name: "volleyball", Category: "Activities", Unicode: "U+1F3D0"},
	{Emoji: "🏉", Name: "rugby_football", Category: "Activities", Unicode: "U+1F3C9"},
	{Emoji: "🥏", Name: "flying_disc", Category: "Activities", Unicode: "U+1F94F"},
	{Emoji: "🎱", Name: "pool_8_ball", Category: "Activities", Unicode: "U+1F3B1"},
	{Emoji: "🏓", Name: "ping_pong", Category: "Activities", Unicode: "U+1F3D3"},
	{Emoji: "🏸", Name: "badminton", Category: "Activities", Unicode: "U+1F3F8"},
	{Emoji: "🏒", Name: "ice_hockey", Category: "Activities", Unicode: "U+1F3D2"},
	{Emoji: "🏑", Name: "field_hockey", Category: "Activities", Unicode: "U+1F3D1"},
	{Emoji: "🥍", Name: "lacrosse", Category: "Activities", Unicode: "U+1F94D"},
	{Emoji: "🏏", Name: "cricket_game", Category: "Activities", Unicode: "U+1F3CF"},
	{Emoji: "🪃", Name: "boomerang", Category: "Activities", Unicode: "U+1FA83"},
	{Emoji: "🥅", Name: "goal_net", Category: "Activities", Unicode: "U+1F945"},
	{Emoji: "⛳", Name: "flag_in_hole", Category: "Activities", Unicode: "U+26F3"},
	{Emoji: "🪁", Name: "kite", Category: "Activities", Unicode: "U+1FA81"},
	{Emoji: "🏹", Name: "bow_and_arrow", Category: "Activities", Unicode: "U+1F3F9"},
	{Emoji: "🎣", Name: "fishing_pole", Category: "Activities", Unicode: "U+1F3A3"},
	{Emoji: "🤿", Name: "diving_mask", Category: "Activities", Unicode: "U+1F93F"},
	{Emoji: "🥊", Name: "boxing_glove", Category: "Activities", Unicode: "U+1F94A"},
	{Emoji: "🥋", Name: "martial_arts_uniform", Category: "Activities", Unicode: "U+1F94B"},
	{Emoji: "🎽", Name: "running_shirt", Category: "Activities", Unicode: "U+1F3BD"},
	{Emoji: "🛹", Name: "skateboard", Category: "Activities", Unicode: "U+1F6F9"},
	{Emoji: "🛷", Name: "sled", Category: "Activities", Unicode: "U+1F6F7"},
	{Emoji: "🥌", Name: "curling_stone", Category: "Activities", Unicode: "U+1F94C"},
	{Emoji: "🎿", Name: "skis", Category: "Activities", Unicode: "U+1F3BF"},
	{Emoji: "⛷️", Name: "skier", Category: "Activities", Unicode: "U+26F7"},
	{Emoji: "🏂", Name: "snowboarder", Category: "Activities", Unicode: "U+1F3C2"},
	{Emoji: "🏋️", Name: "person_lifting_weights", Category: "Activities", Unicode: "U+1F3CB"},
	{Emoji: "🤼", Name: "people_wrestling", Category: "Activities", Unicode: "U+1F93C"},
	{Emoji: "🤸", Name: "person_cartwheeling", Category: "Activities", Unicode: "U+1F938"},
	{Emoji: "⛹️", Name: "person_bouncing_ball", Category: "Activities", Unicode: "U+26F9"},
	{Emoji: "🤺", Name: "person_fencing", Category: "Activities", Unicode: "U+1F93A"},
	{Emoji: "🏇", Name: "horse_racing", Category: "Activities", Unicode: "U+1F3C7"},
	{Emoji: "🧘", Name: "person_in_lotus_position", Category: "Activities", Unicode: "U+1F9D8"},
	{Emoji: "🏄", Name: "person_surfing", Category: "Activities", Unicode: "U+1F3C4"},
	{Emoji: "🏊", Name: "person_swimming", Category: "Activities", Unicode: "U+1F3CA"},
	{Emoji: "🚵", Name: "person_mountain_biking", Category: "Activities", Unicode: "U+1F6B5"},
	{Emoji: "🚴", Name: "person_biking", Category: "Activities", Unicode: "U+1F6B4"},
	{Emoji: "🏆", Name: "trophy", Category: "Activities", Unicode: "U+1F3C6"},
	{Emoji: "🥇", Name: "1st_place_medal", Category: "Activities", Unicode: "U+1F947"},
	{Emoji: "🥈", Name: "2nd_place_medal", Category: "Activities", Unicode: "U+1F948"},
	{Emoji: "🥉", Name: "3rd_place_medal", Category: "Activities", Unicode: "U+1F949"},
	{Emoji: "🏅", Name: "sports_medal", Category: "Activities", Unicode: "U+1F3C5"},
	{Emoji: "🎖️", Name: "military_medal", Category: "Activities", Unicode: "U+1F396"},
	{Emoji: "🏵️", Name: "rosette", Category: "Activities", Unicode: "U+1F3F5"},
	{Emoji: "🎗️", Name: "reminder_ribbon", Category: "Activities", Unicode: "U+1F397"},
	{Emoji: "🎟️", Name: "admission_tickets", Category: "Activities", Unicode: "U+1F39F"},
	{Emoji: "🎫", Name: "ticket", Category: "Activities", Unicode: "U+1F3AB"},
	{Emoji: "🎭", Name: "performing_arts", Category: "Activities", Unicode: "U+1F3AD"},
	{Emoji: "🎨", Name: "artist_palette", Category: "Activities", Unicode: "U+1F3A8"},
	{Emoji: "🎪", Name: "circus_tent", Category: "Activities", Unicode: "U+1F3AA"},
	{Emoji: "🎢", Name: "roller_coaster", Category: "Activities", Unicode: "U+1F3A2"},
	{Emoji: "🎡", Name: "ferris_wheel", Category: "Activities", Unicode: "U+1F3A1"},
	{Emoji: "🎠", Name: "carousel_horse", Category: "Activities", Unicode: "U+1F3A0"},
	{Emoji: "🎰", Name: "slot_machine", Category: "Activities", Unicode: "U+1F3B0"},
	{Emoji: "🎲", Name: "game_die", Category: "Activities", Unicode: "U+1F3B2"},
	{Emoji: "🧩", Name: "puzzle_piece", Category: "Activities", Unicode: "U+1F9E9"},
	{Emoji: "🪅", Name: "pinata", Category: "Activities", Unicode: "U+1FA85"},
	{Emoji: "🎯", Name: "bullseye", Category: "Activities", Unicode: "U+1F3AF"},
	{Emoji: "🎳", Name: "bowling", Category: "Activities", Unicode: "U+1F3B3"},
	{Emoji: "🎮", Name: "video_game", Category: "Activities", Unicode: "U+1F3AE"},
	{Emoji: "🕹️", Name: "joystick", Category: "Activities", Unicode: "U+1F579"},

	// Objects
	{Emoji: "⌚", Name: "watch", Category: "Objects", Unicode: "U+231A"},
	{Emoji: "📱", Name: "mobile_phone", Category: "Objects", Unicode: "U+1F4F1"},
	{Emoji: "💻", Name: "laptop", Category: "Objects", Unicode: "U+1F4BB"},
	{Emoji: "⌨️", Name: "keyboard", Category: "Objects", Unicode: "U+2328"},
	{Emoji: "🖥️", Name: "desktop_computer", Category: "Objects", Unicode: "U+1F5A5"},
	{Emoji: "🖨️", Name: "printer", Category: "Objects", Unicode: "U+1F5A8"},
	{Emoji: "🖱️", Name: "computer_mouse", Category: "Objects", Unicode: "U+1F5B1"},
	{Emoji: "💾", Name: "floppy_disk", Category: "Objects", Unicode: "U+1F4BE"},
	{Emoji: "💿", Name: "optical_disk", Category: "Objects", Unicode: "U+1F4BF"},
	{Emoji: "📀", Name: "dvd", Category: "Objects", Unicode: "U+1F4C0"},
	{Emoji: "🧮", Name: "abacus", Category: "Objects", Unicode: "U+1F9EE"},
	{Emoji: "📷", Name: "camera", Category: "Objects", Unicode: "U+1F4F7"},
	{Emoji: "📸", Name: "camera_with_flash", Category: "Objects", Unicode: "U+1F4F8"},
	{Emoji: "📹", Name: "video_camera", Category: "Objects", Unicode: "U+1F4F9"},
	{Emoji: "🎥", Name: "movie_camera", Category: "Objects", Unicode: "U+1F3A5"},
	{Emoji: "📺", Name: "television", Category: "Objects", Unicode: "U+1F4FA"},
	{Emoji: "📻", Name: "radio", Category: "Objects", Unicode: "U+1F4FB"},
	{Emoji: "🎙️", Name: "studio_microphone", Category: "Objects", Unicode: "U+1F399"},
	{Emoji: "🎚️", Name: "level_slider", Category: "Objects", Unicode: "U+1F39A"},
	{Emoji: "🎛️", Name: "control_knobs", Category: "Objects", Unicode: "U+1F39B"},
	{Emoji: "⏱️", Name: "stopwatch", Category: "Objects", Unicode: "U+23F1"},
	{Emoji: "⏰", Name: "alarm_clock", Category: "Objects", Unicode: "U+23F0"},
	{Emoji: "🕰️", Name: "mantelpiece_clock", Category: "Objects", Unicode: "U+1F570"},
	{Emoji: "⌛", Name: "hourglass_done", Category: "Objects", Unicode: "U+231B"},
	{Emoji: "⏳", Name: "hourglass_not_done", Category: "Objects", Unicode: "U+23F3"},
	{Emoji: "📡", Name: "satellite_antenna", Category: "Objects", Unicode: "U+1F4E1"},
	{Emoji: "🔋", Name: "battery", Category: "Objects", Unicode: "U+1F50B"},
	{Emoji: "🔌", Name: "electric_plug", Category: "Objects", Unicode: "U+1F50C"},
	{Emoji: "💡", Name: "light_bulb", Category: "Objects", Unicode: "U+1F4A1"},
	{Emoji: "🔦", Name: "flashlight", Category: "Objects", Unicode: "U+1F526"},
	{Emoji: "🕯️", Name: "candle", Category: "Objects", Unicode: "U+1F56F"},
	{Emoji: "🪔", Name: "diya_lamp", Category: "Objects", Unicode: "U+1FA94"},
	{Emoji: "🧯", Name: "fire_extinguisher", Category: "Objects", Unicode: "U+1F9EF"},
	{Emoji: "🛢️", Name: "oil_drum", Category: "Objects", Unicode: "U+1F6E2"},
	{Emoji: "💰", Name: "money_bag", Category: "Objects", Unicode: "U+1F4B0"},
	{Emoji: "💴", Name: "yen_banknote", Category: "Objects", Unicode: "U+1F4B4"},
	{Emoji: "💵", Name: "dollar_banknote", Category: "Objects", Unicode: "U+1F4B5"},
	{Emoji: "💸", Name: "money_with_wings", Category: "Objects", Unicode: "U+1F4B8"},
	{Emoji: "💳", Name: "credit_card", Category: "Objects", Unicode: "U+1F4B3"},
	{Emoji: "🧾", Name: "receipt", Category: "Objects", Unicode: "U+1F9FE"},
	{Emoji: "💹", Name: "chart_increasing_with_yen", Category: "Objects", Unicode: "U+1F4B9"},
	{Emoji: "✉️", Name: "envelope", Category: "Objects", Unicode: "U+2709"},
	{Emoji: "📧", Name: "e_mail", Category: "Objects", Unicode: "U+1F4E7"},
	{Emoji: "📨", Name: "incoming_envelope", Category: "Objects", Unicode: "U+1F4E8"},
	{Emoji: "📩", Name: "envelope_with_arrow", Category: "Objects", Unicode: "U+1F4E9"},
	{Emoji: "📤", Name: "outbox_tray", Category: "Objects", Unicode: "U+1F4E4"},
	{Emoji: "📥", Name: "inbox_tray", Category: "Objects", Unicode: "U+1F4E5"},
	{Emoji: "📦", Name: "package", Category: "Objects", Unicode: "U+1F4E6"},
	{Emoji: "📫", Name: "closed_mailbox_with_raised_flag", Category: "Objects", Unicode: "U+1F4EB"},
	{Emoji: "📪", Name: "closed_mailbox_with_lowered_flag", Category: "Objects", Unicode: "U+1F4EA"},
	{Emoji: "📬", Name: "open_mailbox_with_raised_flag", Category: "Objects", Unicode: "U+1F4EC"},
	{Emoji: "📮", Name: "postbox", Category: "Objects", Unicode: "U+1F4EE"},
	{Emoji: "🗳️", Name: "ballot_box_with_ballot", Category: "Objects", Unicode: "U+1F5F3"},
	{Emoji: "✏️", Name: "pencil", Category: "Objects", Unicode: "U+270F"},
	{Emoji: "✒️", Name: "black_nib", Category: "Objects", Unicode: "U+2712"},
	{Emoji: "🖋️", Name: "fountain_pen", Category: "Objects", Unicode: "U+1F58B"},
	{Emoji: "🖊️", Name: "pen", Category: "Objects", Unicode: "U+1F58A"},
	{Emoji: "🖌️", Name: "paintbrush", Category: "Objects", Unicode: "U+1F58C"},
	{Emoji: "🖍️", Name: "crayon", Category: "Objects", Unicode: "U+1F58D"},
	{Emoji: "📝", Name: "memo", Category: "Objects", Unicode: "U+1F4DD"},
	{Emoji: "📁", Name: "file_folder", Category: "Objects", Unicode: "U+1F4C1"},
	{Emoji: "📂", Name: "open_file_folder", Category: "Objects", Unicode: "U+1F4C2"},
	{Emoji: "🗂️", Name: "card_index_dividers", Category: "Objects", Unicode: "U+1F5C2"},
	{Emoji: "📅", Name: "calendar", Category: "Objects", Unicode: "U+1F4C5"},
	{Emoji: "📆", Name: "tear_off_calendar", Category: "Objects", Unicode: "U+1F4C6"},
	{Emoji: "🗒️", Name: "spiral_notepad", Category: "Objects", Unicode: "U+1F5D2"},
	{Emoji: "📇", Name: "card_index", Category: "Objects", Unicode: "U+1F4C7"},
	{Emoji: "📈", Name: "chart_increasing", Category: "Objects", Unicode: "U+1F4C8"},
	{Emoji: "📉", Name: "chart_decreasing", Category: "Objects", Unicode: "U+1F4C9"},
	{Emoji: "📊", Name: "bar_chart", Category: "Objects", Unicode: "U+1F4CA"},
	{Emoji: "📋", Name: "clipboard", Category: "Objects", Unicode: "U+1F4CB"},
	{Emoji: "📌", Name: "pushpin", Category: "Objects", Unicode: "U+1F4CC"},
	{Emoji: "📍", Name: "round_pushpin", Category: "Objects", Unicode: "U+1F4CD"},
	{Emoji: "📎", Name: "paperclip", Category: "Objects", Unicode: "U+1F4CE"},
	{Emoji: "🖇️", Name: "linked_paperclips", Category: "Objects", Unicode: "U+1F587"},
	{Emoji: "📏", Name: "straight_ruler", Category: "Objects", Unicode: "U+1F4CF"},
	{Emoji: "📐", Name: "triangular_ruler", Category: "Objects", Unicode: "U+1F4D0"},
	{Emoji: "✂️", Name: "scissors", Category: "Objects", Unicode: "U+2702"},
	{Emoji: "🗃️", Name: "card_file_box", Category: "Objects", Unicode: "U+1F5C3"},
	{Emoji: "🗄️", Name: "file_cabinet", Category: "Objects", Unicode: "U+1F5C4"},
	{Emoji: "🗑️", Name: "wastebasket", Category: "Objects", Unicode: "U+1F5D1"},
	{Emoji: "🔒", Name: "locked", Category: "Objects", Unicode: "U+1F512"},
	{Emoji: "🔓", Name: "unlocked", Category: "Objects", Unicode: "U+1F513"},
	{Emoji: "🔑", Name: "key", Category: "Objects", Unicode: "U+1F511"},
	{Emoji: "🗝️", Name: "old_key", Category: "Objects", Unicode: "U+1F5DD"},
	{Emoji: "🔨", Name: "hammer", Category: "Objects", Unicode: "U+1F528"},
	{Emoji: "🪓", Name: "axe", Category: "Objects", Unicode: "U+1FA93"},
	{Emoji: "⛏️", Name: "pick", Category: "Objects", Unicode: "U+26CF"},
	{Emoji: "🔧", Name: "wrench", Category: "Objects", Unicode: "U+1F527"},
	{Emoji: "🔩", Name: "nut_and_bolt", Category: "Objects", Unicode: "U+1F529"},
	{Emoji: "⚙️", Name: "gear", Category: "Objects", Unicode: "U+2699"},
	{Emoji: "🗜️", Name: "clamp", Category: "Objects", Unicode: "U+1F5DC"},
	{Emoji: "🔗", Name: "link", Category: "Objects", Unicode: "U+1F517"},
	{Emoji: "⛓️", Name: "chains", Category: "Objects", Unicode: "U+26D3"},
	{Emoji: "🪝", Name: "hook", Category: "Objects", Unicode: "U+1FA9D"},
	{Emoji: "🧲", Name: "magnet", Category: "Objects", Unicode: "U+1F9F2"},
	{Emoji: "🔫", Name: "pistol", Category: "Objects", Unicode: "U+1F52B"},
	{Emoji: "🧨", Name: "firecracker", Category: "Objects", Unicode: "U+1F9E8"},
	{Emoji: "💊", Name: "pill", Category: "Objects", Unicode: "U+1F48A"},
	{Emoji: "🩹", Name: "adhesive_bandage", Category: "Objects", Unicode: "U+1FA79"},
	{Emoji: "🩺", Name: "stethoscope", Category: "Objects", Unicode: "U+1FA7A"},
	{Emoji: "🌡️", Name: "thermometer", Category: "Objects", Unicode: "U+1F321"},
	{Emoji: "🧪", Name: "test_tube", Category: "Objects", Unicode: "U+1F9EA"},
	{Emoji: "🧫", Name: "petri_dish", Category: "Objects", Unicode: "U+1F9EB"},
	{Emoji: "🧬", Name: "dna", Category: "Objects", Unicode: "U+1F9EC"},
	{Emoji: "🔬", Name: "microscope", Category: "Objects", Unicode: "U+1F52C"},
	{Emoji: "🔭", Name: "telescope", Category: "Objects", Unicode: "U+1F52D"},
	{Emoji: "🩻", Name: "x_ray", Category: "Objects", Unicode: "U+1FA7B"},
	{Emoji: "🚪", Name: "door", Category: "Objects", Unicode: "U+1F6AA"},
	{Emoji: "🪞", Name: "mirror", Category: "Objects", Unicode: "U+1FA9E"},
	{Emoji: "🪟", Name: "window", Category: "Objects", Unicode: "U+1FA9F"},
	{Emoji: "🛋️", Name: "couch_and_lamp", Category: "Objects", Unicode: "U+1F6CB"},
	{Emoji: "🪑", Name: "chair", Category: "Objects", Unicode: "U+1FA91"},
	{Emoji: "🚽", Name: "toilet", Category: "Objects", Unicode: "U+1F6BD"},
	{Emoji: "🚿", Name: "shower", Category: "Objects", Unicode: "U+1F6BF"},
	{Emoji: "🛁", Name: "bathtub", Category: "Objects", Unicode: "U+1F6C1"},
	{Emoji: "🧴", Name: "lotion_bottle", Category: "Objects", Unicode: "U+1F9F4"},
	{Emoji: "🧷", Name: "safety_pin", Category: "Objects", Unicode: "U+1F9F7"},
	{Emoji: "🧹", Name: "broom", Category: "Objects", Unicode: "U+1F9F9"},
	{Emoji: "🧺", Name: "basket", Category: "Objects", Unicode: "U+1F9FA"},
	{Emoji: "🧻", Name: "roll_of_paper", Category: "Objects", Unicode: "U+1F9FB"},
	{Emoji: "🚬", Name: "cigarette", Category: "Objects", Unicode: "U+1F6AC"},
	{Emoji: "⚰️", Name: "coffin", Category: "Objects", Unicode: "U+26B0"},
	{Emoji: "🧿", Name: "nazar_amulet", Category: "Objects", Unicode: "U+1F9FF"},
	{Emoji: "🪬", Name: "hamsa", Category: "Objects", Unicode: "U+1FAAC"},
	{Emoji: "🧸", Name: "teddy_bear", Category: "Objects", Unicode: "U+1F9F8"},
	{Emoji: "🪆", Name: "nesting_dolls", Category: "Objects", Unicode: "U+1FA86"},
	{Emoji: "🪄", Name: "magic_wand", Category: "Objects", Unicode: "U+1FA84"},
	{Emoji: "🎩", Name: "top_hat", Category: "Objects", Unicode: "U+1F3A9"},
	{Emoji: "🎓", Name: "graduation_cap", Category: "Objects", Unicode: "U+1F393"},
	{Emoji: "🧳", Name: "luggage", Category: "Objects", Unicode: "U+1F9F3"},
	{Emoji: "💼", Name: "briefcase", Category: "Objects", Unicode: "U+1F4BC"},
	{Emoji: "👑", Name: "crown", Category: "Objects", Unicode: "U+1F451"},
	{Emoji: "💍", Name: "ring", Category: "Objects", Unicode: "U+1F48D"},
	{Emoji: "💎", Name: "gem_stone", Category: "Objects", Unicode: "U+1F48E"},
	{Emoji: "🔮", Name: "crystal_ball", Category: "Objects", Unicode: "U+1F52E"},
	{Emoji: "🧧", Name: "red_envelope", Category: "Objects", Unicode: "U+1F9E7"},
	{Emoji: "🎁", Name: "wrapped_gift", Category: "Objects", Unicode: "U+1F381"},
	{Emoji: "🎀", Name: "ribbon", Category: "Objects", Unicode: "U+1F380"},
	{Emoji: "🎊", Name: "confetti_ball", Category: "Objects", Unicode: "U+1F38A"},
	{Emoji: "🎉", Name: "party_popper", Category: "Objects", Unicode: "U+1F389"},
	{Emoji: "🎈", Name: "balloon", Category: "Objects", Unicode: "U+1F388"},
	{Emoji: "🪩", Name: "mirror_ball", Category: "Objects", Unicode: "U+1FAA9"},
	{Emoji: "🎏", Name: "carp_streamer", Category: "Objects", Unicode: "U+1F38F"},
	{Emoji: "🎐", Name: "wind_chime", Category: "Objects", Unicode: "U+1F390"},
	{Emoji: "🎑", Name: "moon_viewing_ceremony", Category: "Objects", Unicode: "U+1F391"},
	{Emoji: "📿", Name: "prayer_beads", Category: "Objects", Unicode: "U+1F4FF"},
	{Emoji: "✨", Name: "sparkles", Category: "Objects", Unicode: "U+2728"},
	{Emoji: "🔥", Name: "fire", Category: "Objects", Unicode: "U+1F525"},
	{Emoji: "💧", Name: "droplet", Category: "Objects", Unicode: "U+1F4A7"},
	{Emoji: "🌊", Name: "water_wave", Category: "Objects", Unicode: "U+1F30A"},

	// Symbols
	{Emoji: "🔴", Name: "red_circle", Category: "Symbols", Unicode: "U+1F534"},
	{Emoji: "🟠", Name: "orange_circle", Category: "Symbols", Unicode: "U+1F7E0"},
	{Emoji: "🟡", Name: "yellow_circle", Category: "Symbols", Unicode: "U+1F7E1"},
	{Emoji: "🟢", Name: "green_circle", Category: "Symbols", Unicode: "U+1F7E2"},
	{Emoji: "🔵", Name: "blue_circle", Category: "Symbols", Unicode: "U+1F535"},
	{Emoji: "🟣", Name: "purple_circle", Category: "Symbols", Unicode: "U+1F7E3"},
	{Emoji: "⚫", Name: "black_circle", Category: "Symbols", Unicode: "U+26AB"},
	{Emoji: "⚪", Name: "white_circle", Category: "Symbols", Unicode: "U+26AA"},
	{Emoji: "🟤", Name: "brown_circle", Category: "Symbols", Unicode: "U+1F7E4"},
	{Emoji: "🔺", Name: "red_triangle_pointed_up", Category: "Symbols", Unicode: "U+1F53A"},
	{Emoji: "🔻", Name: "red_triangle_pointed_down", Category: "Symbols", Unicode: "U+1F53B"},
	{Emoji: "🔷", Name: "large_blue_diamond", Category: "Symbols", Unicode: "U+1F537"},
	{Emoji: "🔶", Name: "large_orange_diamond", Category: "Symbols", Unicode: "U+1F536"},
	{Emoji: "🔸", Name: "small_orange_diamond", Category: "Symbols", Unicode: "U+1F538"},
	{Emoji: "🔹", Name: "small_blue_diamond", Category: "Symbols", Unicode: "U+1F539"},
	{Emoji: "🔲", Name: "black_square_button", Category: "Symbols", Unicode: "U+1F532"},
	{Emoji: "🔳", Name: "white_square_button", Category: "Symbols", Unicode: "U+1F533"},
	{Emoji: "⬛", Name: "black_large_square", Category: "Symbols", Unicode: "U+2B1B"},
	{Emoji: "⬜", Name: "white_large_square", Category: "Symbols", Unicode: "U+2B1C"},
	{Emoji: "◼️", Name: "black_medium_square", Category: "Symbols", Unicode: "U+25FC"},
	{Emoji: "◻️", Name: "white_medium_square", Category: "Symbols", Unicode: "U+25FB"},
	{Emoji: "▪️", Name: "black_small_square", Category: "Symbols", Unicode: "U+25AA"},
	{Emoji: "▫️", Name: "white_small_square", Category: "Symbols", Unicode: "U+25AB"},
	{Emoji: "🏁", Name: "chequered_flag", Category: "Symbols", Unicode: "U+1F3C1"},
	{Emoji: "🚩", Name: "triangular_flag", Category: "Symbols", Unicode: "U+1F6A9"},
	{Emoji: "🎌", Name: "crossed_flags", Category: "Symbols", Unicode: "U+1F38C"},
	{Emoji: "🏴", Name: "black_flag", Category: "Symbols", Unicode: "U+1F3F4"},
	{Emoji: "🏳️", Name: "white_flag", Category: "Symbols", Unicode: "U+1F3F3"},
	{Emoji: "🏳️‍🌈", Name: "rainbow_flag", Category: "Symbols", Unicode: "U+1F3F3"},
	{Emoji: "✅", Name: "check_mark_button", Category: "Symbols", Unicode: "U+2705"},
	{Emoji: "❎", Name: "cross_mark_button", Category: "Symbols", Unicode: "U+274E"},
	{Emoji: "❌", Name: "cross_mark", Category: "Symbols", Unicode: "U+274C"},
	{Emoji: "⭕", Name: "hollow_red_circle", Category: "Symbols", Unicode: "U+2B55"},
	{Emoji: "🔱", Name: "trident_emblem", Category: "Symbols", Unicode: "U+1F531"},
	{Emoji: "📛", Name: "name_badge", Category: "Symbols", Unicode: "U+1F4DB"},
	{Emoji: "🔰", Name: "japanese_symbol_for_beginner", Category: "Symbols", Unicode: "U+1F530"},
	{Emoji: "💠", Name: "diamond_with_a_dot", Category: "Symbols", Unicode: "U+1F4A0"},
	{Emoji: "🔆", Name: "bright_button", Category: "Symbols", Unicode: "U+1F506"},
	{Emoji: "🔅", Name: "dim_button", Category: "Symbols", Unicode: "U+1F505"},
	{Emoji: "🆚", Name: "vs_button", Category: "Symbols", Unicode: "U+1F19A"},
	{Emoji: "🆕", Name: "new_button", Category: "Symbols", Unicode: "U+1F195"},
	{Emoji: "🆓", Name: "free_button", Category: "Symbols", Unicode: "U+1F193"},
	{Emoji: "🆒", Name: "cool_button", Category: "Symbols", Unicode: "U+1F192"},
	{Emoji: "🆙", Name: "up_button", Category: "Symbols", Unicode: "U+1F199"},
	{Emoji: "🆗", Name: "ok_button", Category: "Symbols", Unicode: "U+1F197"},
	{Emoji: "🆘", Name: "sos_button", Category: "Symbols", Unicode: "U+1F198"},
	{Emoji: "🆔", Name: "id_button", Category: "Symbols", Unicode: "U+1F194"},
	{Emoji: "🔤", Name: "input_latin_letters", Category: "Symbols", Unicode: "U+1F524"},
	{Emoji: "🔡", Name: "input_latin_lowercase", Category: "Symbols", Unicode: "U+1F521"},
	{Emoji: "🔢", Name: "input_numbers", Category: "Symbols", Unicode: "U+1F522"},
	{Emoji: "🔣", Name: "input_symbols", Category: "Symbols", Unicode: "U+1F523"},
	{Emoji: "🔠", Name: "input_latin_uppercase", Category: "Symbols", Unicode: "U+1F520"},
	{Emoji: "📶", Name: "antenna_bars", Category: "Symbols", Unicode: "U+1F4F6"},
	{Emoji: "📳", Name: "vibration_mode", Category: "Symbols", Unicode: "U+1F4F3"},
	{Emoji: "📴", Name: "mobile_phone_off", Category: "Symbols", Unicode: "U+1F4F4"},
	{Emoji: "♻️", Name: "recycling_symbol", Category: "Symbols", Unicode: "U+267B"},
	{Emoji: "⚜️", Name: "fleur_de_lis", Category: "Symbols", Unicode: "U+269C"},
	{Emoji: "✳️", Name: "eight_spoked_asterisk", Category: "Symbols", Unicode: "U+2733"},
	{Emoji: "❇️", Name: "sparkle", Category: "Symbols", Unicode: "U+2747"},
	{Emoji: "🔞", Name: "no_one_under_eighteen", Category: "Symbols", Unicode: "U+1F51E"},
	{Emoji: "⚠️", Name: "warning", Category: "Symbols", Unicode: "U+26A0"},
	{Emoji: "☢️", Name: "radioactive", Category: "Symbols", Unicode: "U+2622"},
	{Emoji: "☣️", Name: "biohazard", Category: "Symbols", Unicode: "U+2623"},
	{Emoji: "🔔", Name: "bell", Category: "Symbols", Unicode: "U+1F514"},
	{Emoji: "🔕", Name: "bell_with_slash", Category: "Symbols", Unicode: "U+1F515"},
	{Emoji: "🎵", Name: "musical_note", Category: "Symbols", Unicode: "U+1F3B5"},
	{Emoji: "🎶", Name: "musical_notes", Category: "Symbols", Unicode: "U+1F3B6"},
	{Emoji: "🔉", Name: "medium_volume_speaker", Category: "Symbols", Unicode: "U+1F509"},
	{Emoji: "🔊", Name: "high_volume_speaker", Category: "Symbols", Unicode: "U+1F50A"},
	{Emoji: "🔇", Name: "muted_speaker", Category: "Symbols", Unicode: "U+1F507"},
	{Emoji: "📣", Name: "megaphone", Category: "Symbols", Unicode: "U+1F4E3"},
	{Emoji: "📢", Name: "loudspeaker", Category: "Symbols", Unicode: "U+1F4E2"},
	{Emoji: "♈", Name: "aries", Category: "Symbols", Unicode: "U+2648"},
	{Emoji: "♉", Name: "taurus", Category: "Symbols", Unicode: "U+2649"},
	{Emoji: "♊", Name: "gemini", Category: "Symbols", Unicode: "U+264A"},
	{Emoji: "♋", Name: "cancer", Category: "Symbols", Unicode: "U+264B"},
	{Emoji: "♌", Name: "leo", Category: "Symbols", Unicode: "U+264C"},
	{Emoji: "♍", Name: "virgo", Category: "Symbols", Unicode: "U+264D"},
	{Emoji: "♎", Name: "libra", Category: "Symbols", Unicode: "U+264E"},
	{Emoji: "♏", Name: "scorpio", Category: "Symbols", Unicode: "U+264F"},
	{Emoji: "♐", Name: "sagittarius", Category: "Symbols", Unicode: "U+2650"},
	{Emoji: "♑", Name: "capricorn", Category: "Symbols", Unicode: "U+2651"},
	{Emoji: "♒", Name: "aquarius", Category: "Symbols", Unicode: "U+2652"},
	{Emoji: "♓", Name: "pisces", Category: "Symbols", Unicode: "U+2653"},
	{Emoji: "⛎", Name: "ophiuchus", Category: "Symbols", Unicode: "U+26CE"},
	{Emoji: "🔀", Name: "shuffle_tracks_button", Category: "Symbols", Unicode: "U+1F500"},
	{Emoji: "🔁", Name: "repeat_button", Category: "Symbols", Unicode: "U+1F501"},
	{Emoji: "🔂", Name: "repeat_single_button", Category: "Symbols", Unicode: "U+1F502"},
	{Emoji: "▶️", Name: "play_button", Category: "Symbols", Unicode: "U+25B6"},
	{Emoji: "⏩", Name: "fast_forward_button", Category: "Symbols", Unicode: "U+23E9"},
	{Emoji: "⏭️", Name: "next_track_button", Category: "Symbols", Unicode: "U+23ED"},
	{Emoji: "⏯️", Name: "play_or_pause_button", Category: "Symbols", Unicode: "U+23EF"},
	{Emoji: "◀️", Name: "reverse_button", Category: "Symbols", Unicode: "U+25C0"},
	{Emoji: "⏪", Name: "fast_reverse_button", Category: "Symbols", Unicode: "U+23EA"},
	{Emoji: "⏮️", Name: "last_track_button", Category: "Symbols", Unicode: "U+23EE"},
	{Emoji: "🔼", Name: "upwards_button", Category: "Symbols", Unicode: "U+1F53C"},
	{Emoji: "⏫", Name: "fast_up_button", Category: "Symbols", Unicode: "U+23EB"},
	{Emoji: "🔽", Name: "downwards_button", Category: "Symbols", Unicode: "U+1F53D"},
	{Emoji: "⏬", Name: "fast_down_button", Category: "Symbols", Unicode: "U+23EC"},
	{Emoji: "⏸️", Name: "pause_button", Category: "Symbols", Unicode: "U+23F8"},
	{Emoji: "⏹️", Name: "stop_button", Category: "Symbols", Unicode: "U+23F9"},
	{Emoji: "⏺️", Name: "record_button", Category: "Symbols", Unicode: "U+23FA"},
	{Emoji: "🔃", Name: "clockwise_vertical_arrows", Category: "Symbols", Unicode: "U+1F503"},
	{Emoji: "➕", Name: "plus", Category: "Symbols", Unicode: "U+2795"},
	{Emoji: "➖", Name: "minus", Category: "Symbols", Unicode: "U+2796"},
	{Emoji: "➗", Name: "division_sign", Category: "Symbols", Unicode: "U+2797"},
	{Emoji: "✖️", Name: "multiplication_sign", Category: "Symbols", Unicode: "U+2716"},
	{Emoji: "♾️", Name: "infinity", Category: "Symbols", Unicode: "U+267E"},
	{Emoji: "💲", Name: "heavy_dollar_sign", Category: "Symbols", Unicode: "U+1F4B2"},
	{Emoji: "©️", Name: "copyright", Category: "Symbols", Unicode: "U+00A9"},
	{Emoji: "®️", Name: "registered", Category: "Symbols", Unicode: "U+00AE"},
	{Emoji: "™️", Name: "trade_mark", Category: "Symbols", Unicode: "U+2122"},
	{Emoji: "❓", Name: "question_mark", Category: "Symbols", Unicode: "U+2753"},
	{Emoji: "❔", Name: "white_question_mark", Category: "Symbols", Unicode: "U+2754"},
	{Emoji: "❕", Name: "white_exclamation_mark", Category: "Symbols", Unicode: "U+2755"},
	{Emoji: "❗", Name: "exclamation_mark", Category: "Symbols", Unicode: "U+2757"},
	{Emoji: "‼️", Name: "double_exclamation_mark", Category: "Symbols", Unicode: "U+203C"},
	{Emoji: "⁉️", Name: "exclamation_question_mark", Category: "Symbols", Unicode: "U+2049"},
	{Emoji: "⚛️", Name: "atom_symbol", Category: "Symbols", Unicode: "U+269B"},
	{Emoji: "🕉️", Name: "om", Category: "Symbols", Unicode: "U+1F549"},
	{Emoji: "✡️", Name: "star_of_david", Category: "Symbols", Unicode: "U+2721"},
	{Emoji: "☸️", Name: "wheel_of_dharma", Category: "Symbols", Unicode: "U+2638"},
	{Emoji: "☯️", Name: "yin_yang", Category: "Symbols", Unicode: "U+262F"},
	{Emoji: "✝️", Name: "latin_cross", Category: "Symbols", Unicode: "U+271D"},
	{Emoji: "☦️", Name: "orthodox_cross", Category: "Symbols", Unicode: "U+2626"},
	{Emoji: "🛐", Name: "place_of_worship", Category: "Symbols", Unicode: "U+1F6D0"},
	{Emoji: "🕎", Name: "menorah", Category: "Symbols", Unicode: "U+1F54E"},
	{Emoji: "☮️", Name: "peace_symbol", Category: "Symbols", Unicode: "U+262E"},
	{Emoji: "🔯", Name: "dotted_six_pointed_star", Category: "Symbols", Unicode: "U+1F52F"},
}
